LibreSign/libresign

- lib/Controller/PageController.php
- src/Components/Description.vue
- src/Components/PDFViewer.vue
- src/views/External.vue
> External route

- lib/Controller/PageController.php
- Security Policy to access data in external route.
> Secutiry Policy for acessing data on an external route.

- docs/API.md
- lib/Db/FileUser.php
- lib/Helper/JSConfigHelper.php
- lib/Migration/Version1000Date20210209004203.php
- lib/Migration/Version1000Date20210209011129.php
- lib/Service/MailService.php
- lib/Service/WebhookService.php
> Refactor rename field

- appinfo/info.xml
> Bump max nextloud version

- lib/Controller/LibresignController.php
- lib/Db/FileUserMapper.php
- lib/Service/WebhookService.php
- tests/Unit/Controller/LibresignControllerTest.php
> Feature notify callback

- lib/Helper/JSConfigHelper.php
- src/Components/Description/Description.vue
- src/middlewares/searchAction.js
- src/router/router.js
- src/views/SignPDF.vue
> Route sign document

- src/router/router.js
- src/views/CreateUser.vue
- Pass the user a toast stating that they have not found a user related to the email.
> Pass error message through route props

- lib/Controller/LibresignController.php
> error handler

- lib/Helper/JSActions.php
- lib/Helper/JSConfigHelper.php
- lib/Service/WebhookService.php
Response of backend:
```json
"libresign":{"action":300,"errors":["File already signed."]}
```
> Show error when user already signed the file

- appinfo/routes.php
- lib/Controller/WebhookController.php
- lib/Db/FileUserMapper.php
- lib/Service/FolderService.php
- lib/Service/WebhookService.php
> Delete sign request

- src/Components/Description/styles.scss
- src/external.js
- src/middlewares/SelectAction.js
- src/store/index.js
- src/views/CreateUser.vue
- src/views/SignPDF.vue
When creating a user add document data in redux, when loading the page take the data from redux and check if there is a local variable in the html.
> Redux Struture for persistence of data

- Makefile
- package.json
- webpack.dev.js
- webpack.prod.js
> Fix package size

- Makefile
- composer.json
- composer.lock
* Add generate sign key
* Change dependency jsignpdf repository
> Makefile and change dependency repository

- .tx/config
For https://github.com/nextcloud/docker-ci/commit/e0c2cb9a0964617729e9f52f99708e2e49d4d5ac
> Fix langmap config

- lib/Controller/LibresignController.php
Standardizing text strings with other Nextcloud applications.
> l10n: Change to singular

- lib/Controller/LibresignController.php
> Change text

- lib/Service/WebhookService.php
- tests/Unit/Service/WebhookServiceTest.php
> Replace collection by list

- src/views/LibresignTab.vue
> Change var name and fix translation

- lib/Service/AccountService.php
- tests/Unit/Service/AccountServiceTest.php
> l10n: Change error message of file

- src/views/Settings.vue
- src/views/UrlValidation.vue
Field to enter the URL that will validate the signed documents.
> url validation field

- lib/Service/WebhookService.php
> Force email to lowercase

- src/assets/styles/CreateUser.scss
- src/views/CreateUser.vue
Disable the create new user button to avoid multiple requests to the backend.
> disable-btn

- src/assets/styles/CreateUser.scss
- src/views/CreateUser.vue
* JS/CSS
*  Fluid button animation and scalability
* UX:
* the button's text can now not be selected
> Disable create account button when submitting form

- src/views/UrlValidation.vue
default placeholder url(validate document) in libresign settings.
> default placeholder url 

- docs/Getting-started.md
- lib/Service/AccountService.php
- lib/Service/FolderService.php
- lib/Service/WebhookService.php
- tests/Unit/Service/WebhookServiceTest.php
Added possibility to request the signing of a file using the nodeId
> Sign using nodeid

- src/Components/Request/Request.vue
- src/views/LibresignTab.vue
- src/views/Validation.vue
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Correct text strings

- lib/Service/WebhookService.php
- src/views/Validation.vue
- tests/Unit/Service/WebhookServiceTest.php
1. Changed "fileId" to "fileID".
2. Change to capital letter.
> l10n: Correct spelling

- lib/Service/WebhookService.php
> Fix mistake in WebhookService::getFileUser()

- CHANGELOG.md
- src/Components/File/Sidebar.vue
- src/views/Timeline.vue
Filters files whose signature status is pending, signed, or show all
> Filter files

- src/Components/Description/Description.vue
> Fixed grammar

- src/Components/File/SignaturesTab.vue
> Fixed typo

- CHANGELOG.md
- lib/Controller/SignFileController.php
- lib/Db/File.php
- lib/Db/FileMapper.php
- lib/Handler/Pkcs12Handler.php
- lib/Migration/Version2040Date20210730022217.php
- lib/Service/AccountService.php
- lib/Service/SignFileService.php
- tests/Unit/Service/AccountServiceTest.php
> Add sign UUID to return of sign method

- CHANGELOG.md
- lib/Controller/AccountController.php
- lib/Controller/SignFileController.php
- lib/Db/File.php
- lib/Db/FileMapper.php
- lib/Handler/Pkcs12Handler.php
- lib/Migration/Version2040Date20210730022217.php
- lib/Service/AccountService.php
- lib/Service/SignFileService.php
- tests/Unit/Service/AccountServiceTest.php
> Remove required sign password

- jsconfig.json
- src/Components/Description/Description.vue
- src/Components/File/Sidebar.vue
- src/Components/File/SignaturesTab.vue
- src/Components/Sign/Sign.vue
- src/__test__/unit/Timeline.spec.js
- src/router/router.js
- src/store/index.js
- src/store/modules/errors.js
- src/store/modules/files.js
- src/store/modules/sidebar.js
- src/store/modules/sign.js
- src/store/modules/validate.js
- src/views/DefaultPageError.vue
- src/views/DefaultPageSuccess.vue
- src/views/Request.vue
- src/views/Timeline.vue
refactoring store, adding modules and requests to API via vuex.
> Refactor Store

- CHANGELOG.md
- src/init.js
- src/main.js
- src/settings.js
- src/store/index.js
- src/store/modules/f_controller.js
This PR serves to enable and disable features that are released and the user can choose if he wants in his application.
To enable Feature use a Global variable LibreSign.
Enable features: window.OCA.LibreSign.enableFeature(FEATURE_NAME)
Get available features: window.OCA.LibreSign.getFeatures()
> Controller features

- lib/Helper/ValidateHelper.php
- tests/Unit/Helper/ValidateHelperTest.php
Translator's report from Transifex.
> l10n: Correct sentence

- lib/Helper/ValidateHelper.php
> Changed grammar

- lib/Helper/ValidateHelper.php
Added translator comment as well.
> Extended exception message

- src/views/SignDetail/SignDetail.vue
> l10n: Fixed typo

- src/views/SignPDF/_partials/Sign.vue
> l10n: Changed grammar

- src/views/Account/partials/Documents.vue
> l10n: Change columnen header to uppercase

- lib/Controller/SignFileController.php
- lib/Controller/SignFileDeprecatedController.php
Please ask if questions remain, I think its self-explanatory.
> Fix a non-defaulted function-argement listed after defaulted function arguments.

- appinfo/info.xml
> [stable23] Remove java dependency from info.xml

- appinfo/info.xml
> [stable22] Remove java dependency from info.xml

- appinfo/info.xml
> [stable21] Remove java dependency from info.xml

- composer.lock
- lib/Service/PdfParserService.php
> Fix path of file

- lib/Service/PdfParserService.php
backport of https://github.com/LibreSign/libresign/pull/812
> [stable24] Fix path of file

- composer.json
- composer.lock
- lib/Service/PdfParserService.php
> [stable22] Fix path of file

- lib/Service/InstallService.php
> [stable24] Download improvements: verify hash

- lib/Service/PdfParserService.php
> [stable24] Remove get libresign-cli from constructor

- .github/workflows/node.yml
> [stable24] Check node

- .github/workflows/node.yml
> [stable23] Check node

- README.md
> [stable24] Resume README.md

- README.md
> [stable23] Resume README.md

- src/views/Settings/AdminFormLibresign.vue
- src/views/Settings/AllowedGroups.vue
- src/views/Settings/UrlValidation.vue
> Fix field size

- src/views/Settings/DownloadBinaries.vue
> l10n: Fixed unit name

- src/views/Settings/DownloadBinaries.vue
> l10n: Improved wording

- src/Components/Request/Request.vue
> Update to NcButton

- src/views/Settings/SignPage.vue
> l10n: Fixed typo and grammar

- src/views/Settings/ConfigureCheck.vue
> Text modification

- composer.lock
- lib/Handler/JSignPdfHandler.php
- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
> [stable24] Bump JSignPdf and add ability to check if is usign the valid version

- composer.lock
- lib/Handler/JSignPdfHandler.php
- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
> [stable23] Bump JSignPdf and add ability to check if is usign the valid version

- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
> [stable24] Bug Fix: Install

- CHANGELOG.md
- appinfo/info.xml
- package.json
> [stable24] Changelog

- CHANGELOG.md
- appinfo/info.xml
- package.json
> [stable23] Changelog

- CHANGELOG.md
- appinfo/info.xml
- package.json
- src/views/CreatePassword.vue
> [stable25] Fix position of element

- .github/FUNDING.yml
> Add github sponsor

- lib/Helper/ValidateHelper.php
Clarifies the signature file validation method exception message.
Closes #806
> Improve exception message

- CHANGELOG.md
- appinfo/info.xml
> [stable25] Update changelog

- lib/Command/Configure/Cfssl.php
> Fix command to configure root cert by cli

- .github/workflows/integration.yml
> [stable25] Postgres Version

- .github/workflows/integration.yml
> [stable24] Postgres Version

- .github/workflows/integration.yml
> [stable23] Postgres Version

- lib/Helper/ValidateHelper.php
Reverted change of 64f9bc0417da4ef131c15995f2e94f1cf1e0b9d8
Reported at Transifex and confirmed.
> l10n: Fixed grammar

- lib/Helper/ValidateHelper.php
> [stable25] l10n: Fixed grammar

- lib/Helper/ValidateHelper.php
> [stable24] l10n: Fixed grammar

- lib/Helper/ValidateHelper.php
> [stable23] l10n: Fixed grammar

- CHANGELOG.md
- appinfo/info.xml
- package.json
> [stable25] Bump release

- lib/Handler/JSignPdfHandler.php
> Fix temp dir

- CHANGELOG.md
- appinfo/info.xml
> [stable25] Changelog

- CHANGELOG.md
- lib/Handler/JSignPdfHandler.php
> [stable25] Bugfix temp path

- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
- package-lock.json
- package.json
> Bugfix: configure check

- lib/Service/InstallService.php
> Handle error

- lib/Migration/Version2040Date20211027183759.php
- lib/Service/PdfParserService.php
- lib/Service/SignFileService.php
- tests/Unit/Service/PdfParseServiceTest.php
> Read metadata of shared file

- README.md
- lib/Service/AdminSignatureService.php
- src/views/Settings/RootCertificate.vue
> Frontend improvements to generate root cert

- composer.lock
- lib/Service/InstallService.php
- vendor-bin/coding-standard/composer.lock
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
The setup on web interface start background process to each binary necessary to download and each process store the progress at memcache. If the instance haven't memcache, the progress bar didn't displayed.
To fix I put a fallback to use a json file to store the download progress of all when haven't memcache.
> Show progress bar when havent memcache

- lib/Handler/Pkcs12Handler.php
- src/views/Settings/RootCertificate.vue
- tests/Api/Controller/AccountControllerTest.php
- tests/Api/Controller/SignFileControllerTest.php
* Fix to get key as id of custom name attribute of certificate
* Send text to translation
> Bugfixes and translation

- CHANGELOG.md
- appinfo/info.xml
> [stable25] Bump app version and update CHANGELOG

- package-lock.json
- package.json
> [stable25] Build(deps-dev): Bump jest from 29.4.2 to 29.4.3

- Makefile
> [stable25] Fix makefile appstore target

- Makefile
> Fix missing signed htaccess

- package-lock.json
What I did:
```
npm update
```
> Bump node dependencies

- src/views/Settings/CollectMetadata.vue
Minor grammar fixes for CollectMetadata.vue
> Grammar fixes for Metadata messages

- .github/workflows/integration.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/phpunit.yml
- .github/workflows/psalm.yml
> [stable26] Limit execution of backend tests

- src/views/Settings/CollectMetadata.vue
> Spelling fixes for metadata messages

- CHANGELOG.md
- appinfo/info.xml
> [stable25] Add changelog for 6.2.9

- composer.lock
- lib/Migration/Version7000Date20230327094452.php
- tests/integration/composer.lock
- vendor-bin/coding-standard/composer.lock
- vendor-bin/psalm/composer.lock
Convert rootCert to newest format
> Bugfix root cert

- package-lock.json
- package.json
- src/Components/Draw/Editor.vue
- src/views/Account/partials/Signatures.vue
Now we haven't frontend implementation to add initial to a PDF, then was disabled to users to create initials.
When we click to save the signature, throw an error, fixed this problem
> Hide initial and fix save signature modal

- lib/Helper/ValidateHelper.php
- tests/Unit/Helper/ValidateHelperTest.php
- tests/Unit/Service/AccountServiceTest.php
- tests/Unit/Service/SignFileServiceTest.php
Make sure the file mime is pdf
Closes #903
> Increase PDF validation

- lib/Helper/ValidateHelper.php
- src/Components/Draw/FileUpload.vue
- src/Components/Draw/TextInput.vue
- src/views/Account/partials/Signature.vue
* Fixed problem at modal that don't close
* Fixed the mimetype validation when is a base64 string of image
> Fix save signature as image

- lib/Service/FolderService.php
- src/views/CreatePassword.vue
- src/views/Settings/DefaultUserFolder.vue
- src/views/Settings/Settings.vue
close https://github.com/LibreSign/libresign/issues/1557
> Make possible change the default user folder

- CHANGELOG.md
- appinfo/info.xml
> [stable26] Changelog

- composer.json
- composer.lock
- lib/Command/Base.php
- lib/Command/Install.php
- lib/Command/Uninstall.php
- lib/Controller/AdminController.php
- lib/Migration/Version8000Date20230410230327.php
- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
- lib/Service/PdfParserService.php
- src/views/Settings/DownloadBinaries.vue
- tests/Unit/Service/PdfParseServiceTest.php
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
Used this solution: https://github.com/smalot/pdfparser/issues/427#issuecomment-973416786
Close: #1428
> Drop libresign cli

- .github/config.yml
- .github/workflows/command-rebase.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php.yml
* Add "thanks for contributing" at the new PR
* Add Action to parse to info.xml
* Add Action to apply php linter
* Add Action to implement command /rebase
> Improvements at GitHub Actions

- .github/workflows/behat.yml
- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/config/behat.yml
- tests/integration/features/page/sign.feature
- tests/integration/features/sign/request.feature
> [stable26] Verify email sent

- src/Components/Draw/Editor.vue
- src/Components/PreviewSignature/PreviewSignature.vue
- src/Components/PreviewSignature/index.js
- src/views/Account/partials/Signature.vue
- src/views/SignPDF/_partials/Sign.vue
close issue #1461 
replicate the style of canvas
In dark mode:
In Light mode:
> fix: style preview signatur modal like canva style

- .github/workflows/behat.yml
- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/config/behat.yml
- tests/integration/features/page/sign.feature
- tests/integration/features/sign/request.feature
> [stable25] Verify email sent

- CHANGELOG.md
- appinfo/info.xml
> [stable26] Add changelog

- CHANGELOG.md
- appinfo/info.xml
> [stable25] Add changelog

- src/Components/PreviewSignature/PreviewSignature.vue
Removed src from data and maintained only at props
> If is a prop, can't be a data.

- src/views/Settings/IdentifierFactor.vue
- fix button behaviors in useSMS and useSignal
> fix: swipe buttons useSignal and useSMS

- src/views/Settings/IdentifierFactor.vue
Fix console error because the component `NcSettingsSection` need to have a description
> Fix: add description

- tests/Unit/Controller/PageControllerTest.php
- tests/Unit/Handler/JSignPdfHandlerTest.php
- tests/Unit/Handler/Pkcs12HandlerTest.php
- tests/Unit/Helper/ConfigureCheckHelperTest.php
- tests/Unit/Helper/ValidateHelperTest.php
- tests/Unit/Service/AccountFileServiceTest.php
- tests/Unit/Service/AccountServiceTest.php
- tests/Unit/Service/InstallServiceTest.php
- tests/Unit/Service/MailServiceTest.php
- tests/Unit/Service/PdfParseServiceTest.php
- tests/Unit/Service/RequestSignatureServiceTest.php
- tests/Unit/Service/SignFileServiceTest.php
- tests/Unit/Settings/AdminSettingsTest.php
- tests/Unit/Settings/AdminTest.php
Reference:
https://3v4l.org/ArLAg
https://www.php.net/manual/en/language.types.declarations.php
> Move annotation to union types

- lib/AppInfo/Application.php
- lib/Events/ASignedEvent.php
- lib/Events/SignedEvent.php
- lib/Listener/SignedListener.php
- lib/Service/SignFileService.php
Follow the pattern of other apps and use the folder name in plural
> Rename folder Event to Events

- src/views/Settings/DownloadBinaries.vue
ref: https://nextcloud-vue-components.netlify.app/#/Components/NcProgressBar
> Remove error flag

- lib/Db/FileUserMapper.php
This is necessary in frontend to make other requests to API using UUID
> Return UUID in file object

- src/Components/Request/IdentifySigner.vue
Will be necessary improve this code in the future because would be best return the email as value of identify method and not as property of signer
> Display email

- src/views/Settings/ConfigureCheck.vue
> Change advice to tip

- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
> Remove dots from texts at admin page

- src/views/Settings/IdentifierFactor.vue
> Fix translation text

- lib/Controller/AEnvironmentPageAwareController.php
- lib/Controller/PageController.php
- src/App.vue
- src/helpers/SelectAction.js
- src/router/router.js
- src/store/index.js
- src/store/modules/settings.js
- src/views/CreateUser.vue
- src/views/DefaultPageSuccess.vue
- src/views/Settings/Settings.vue
- src/views/Settings/Validation.vue
- src/views/SignPDF/SignPDF.vue
- src/views/Validation.vue
- tests/integration/features/page/validate.feature
- tests/psalm-baseline.xml
> Make validation page public or private

- lib/Controller/PageController.php
> Add rate limit to non users

- lib/Command/Configure/Check.php
- lib/Handler/CertificateEngine/Handler.php
- lib/Handler/CertificateEngine/IEngineHandler.php
- lib/Handler/CertificateEngine/NoneHandler.php
- src/views/Settings/CertificateEngine.vue
> Make possible to do not use root certificate

- CONTRIBUTING.md
- README.md
> Update contributing and readme

- vendor-bin/coding-standard/composer.lock
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
The minimum PHP of server is 8.0
> Fix the PHP vendor version to be compatible with PHP8.0

- .github/workflows/behat.yml
- appinfo/routes.php
- appinfo/routes/routesDevelopController.php
- lib/Controller/DevelopController.php
- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/config/behat.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/page/sign_identify_default.feature
- tests/integration/features/sign/request.feature
> [stable28] Add test to upload as url

- composer.lock
- vendor-bin/phpunit/composer.lock
> [stable28] Bump dependencies

- appinfo/routes/routesPageController.php
- lib/Controller/AEnvironmentPageAwareController.php
- lib/Controller/PageController.php
- lib/Db/IdentifyMethod.php
- lib/Helper/JSActions.php
- lib/Helper/ValidateHelper.php
- lib/Middleware/Attribute/CanSignRequestUuid.php
- lib/Middleware/InjectionMiddleware.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/IdentifyMethod/Account.php
- lib/Service/IdentifyMethod/Email.php
- lib/Service/IdentifyMethod/IIdentifyMethod.php
- lib/Service/IdentifyMethod/Password.php
- lib/Service/RequestSignatureService.php
- lib/Service/SignFileService.php
- tests/Unit/Controller/AEnvironmentPageAwareControllerTest.php
- tests/Unit/Service/RequestSignatureServiceTest.php
- tests/integration/composer.lock
- tests/integration/features/account/create_to_sign.feature
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/page/sign_identify_account.feature
- tests/integration/features/sign/request.feature
- tests/psalm-baseline.xml
To change the expire rules is necessary the follow PR otherwise will be necessary change the settings by occ has was made at integration tests.
- https://github.com/LibreSign/libresign/pull/2019
> Validate expired link server side

- .editorconfig
https://github.com/nextcloud/server/blob/master/.editorconfig
> Follow the same rules as Nextcloud server

- src/router/router.js
If the URL has index.php we don't will rewrite the URL.
Reference: https://github.com/nextcloud/spreed/blob/main/src/router/router.js#L41-L49
> Identify when the route has index.php

- src/router/router.js
Reference: https://v3.router.vuejs.org/guide/essentials/nested-routes.html
> Use nested routes

- src/router/router.js
A nested router neet to be rendered inside the component of main router, this will be complex for now, reverting the PR
> Revert previous commit

- appinfo/routes/routesPageController.php
- appinfo/routes/routesSignFileController.php
- composer.json
- composer.lock
- lib/Controller/AEnvironmentPageAwareController.php
- lib/Controller/LibresignTrait.php
- lib/Controller/PageController.php
- lib/Controller/SignFileController.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/RequestSignatureService.php
- lib/Service/SignFileService.php
- src/views/RenewEmail.vue
- tests/Unit/Service/RequestSignatureServiceTest.php
- tests/Unit/Service/SignFileServiceTest.php
- tests/integration/features/sign/request.feature
- tests/psalm-baseline.xml
> Renew sign link that was sent by email

- appinfo/routes/routesPageController.php
- appinfo/routes/routesSignFileController.php
- composer.json
- composer.lock
- lib/Controller/AEnvironmentPageAwareController.php
- lib/Controller/LibresignTrait.php
- lib/Controller/PageController.php
- lib/Controller/SignFileController.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/RequestSignatureService.php
- lib/Service/SignFileService.php
- src/views/RenewEmail.vue
- tests/Unit/Service/RequestSignatureServiceTest.php
- tests/Unit/Service/SignFileServiceTest.php
- tests/integration/features/sign/request.feature
- tests/psalm-baseline.xml
> [stable28]  Renew sign link that was sent by email

- package-lock.json
- package.json
> [stable28] Chore(deps): Bump vue and vue-template-compiler

- package-lock.json
- package.json
For now `vue/cli-plugin-unit-jest` isn't used at LibreSign
> Remove unused dependency and bump other dependencies

- src/views/Request.vue
> Add loading icon

- src/views/Request.vue
> [stable28] Add loading icon

- src/views/Request.vue
When we got an upload error, is necessary to be possible try again
> Enable send after error

- src/Components/Request/RequestSignature.vue
- src/Components/Request/VisibleElements.vue
- src/views/Settings/ConfigureCheck.vue
- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
- src/views/Timeline/Timeline.vue
Remove subscribe event when the component is unmounted
> Implement unsubscribe

- lib/Controller/PageController.php
- lib/Helper/ValidateHelper.php
- lib/Service/FileElementService.php
- lib/Service/FileService.php
- package-lock.json
- package.json
- src/Components/Nextcloud/NcDialog/NcDialog.vue
- src/Components/PdfEditor/PdfEditor.vue
- src/Components/PdfEditor/Signature.vue
- src/Components/Request/VisibleElements.vue
- src/domains/sign/service.js
- webpack.config.js
> [stable28]  Display PDF document with lib #1996

- src/Components/Request/VisibleElements.vue
> Fix var of signer uuid

- src/Components/ProgressBar.vue
- src/Components/Request/SignDetail/partials/PageNavigation.vue
- src/views/Account/partials/Documents.vue
- src/views/Account/partials/Signatures.vue
- src/views/Documents/AccountValidation.vue
- src/views/SignPDF/_partials/ModalEmailManager.vue
- src/views/SignPDF/_partials/ModalSMSManager.vue
- src/views/SignPDF/_partials/Sign.vue
Follow the pattern of other .vue files
> Move template to begin

- src/views/Account/partials/Documents.vue
Changed from config.settings.identificationDOcumentsFlow to config.identificationDocumentsFlow
> Fix the initial state name

- src/Components/PdfEditor/PdfEditor.vue
- src/Components/PdfEditor/Signature.vue
> Readonly signatore

- .github/pull_request_template.md
Since it's an open source project and he is growing is important to have standardization.
Issue Number: #1974
Please check the type of change your pull request introduces:
- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Other (please describe):
> Create template for pull request

- src/views/Request.vue
|Before|After|
|---|---|
|![Screenshot_20240119_103641](https://github.com/LibreSign/libresign/assets/1079143/c63a43d2-0fd6-4e0d-bc48-895271d9748e)|![Screenshot_20240119_103608](https://github.com/LibreSign/libresign/assets/1079143/7788c450-4329-4d13-a8db-36e7c666cd6e)|
> Fix layout of buttons at request signatures page

- src/Components/PdfEditor/Signature.vue
|Before|After|
|---|---|
|![Screenshot_20240119_112035](https://github.com/LibreSign/libresign/assets/1079143/a2dabed8-03c9-4111-b0b4-795f24b1a223)|![Screenshot_20240119_112000](https://github.com/LibreSign/libresign/assets/1079143/a616e434-dd2e-4d65-b339-f6b9b550a183)|
> Add background to signature element

- lib/Helper/ValidateHelper.php
> Add translator help

- lib/Helper/ValidateHelper.php
> [stable28] Add translator help

- src/Components/Request/IdentifySigner.vue
|before|after|
|---|---|
|![Screenshot_20240122_180642](https://github.com/LibreSign/libresign/assets/1079143/497db2a1-066e-42b9-8740-45f2de76f32c)|![Screenshot_20240122_180615](https://github.com/LibreSign/libresign/assets/1079143/6efb9642-2f53-4c3a-93d1-bf477136547f)|
> Use display name when is email

- src/views/CreatePassword.vue
- src/views/SignPDF/_partials/Sign.vue
|before|after|
|---|---|
|![Screenshot_20240122_183658](https://github.com/LibreSign/libresign/assets/1079143/6133d213-a325-43d2-abad-b4f3b1fe8f07)|![Screenshot_20240122_183625](https://github.com/LibreSign/libresign/assets/1079143/8d74e269-6ac3-4780-ad17-b60e2e20a461)|
> Remove unused css

- src/App.vue
|Before|After|
|---|---|
|![Screenshot_20240124_144236](https://github.com/LibreSign/libresign/assets/1079143/bd8e6c9d-9c40-4ae7-bbb8-0cd859e59b53)|![Screenshot_20240124_144218](https://github.com/LibreSign/libresign/assets/1079143/6fa89e47-7d3a-4a1f-a20d-edcb78e52e76)|
> Fix css of menu

- src/Components/Draw/Draw.vue
- src/Components/File/Sidebar.vue
- src/Components/Request/SignDetail/partials/SignerRow.vue
- src/Components/Signers/Signer.vue
- src/router/router.js
- src/views/CreatePassword.vue
- src/views/Settings/AllowedGroups.vue
- src/views/Settings/CertificateCustonOptions.vue
- src/views/Settings/ExpirationRules.vue
- src/views/Settings/IdentificationDocuments.vue
- src/views/Settings/Validation.vue
Fix components after upgrade Nextcloud Vue
> Organize components

- src/Components/Request/VisibleElements.vue
> Sign-details div should be fixed on top

- src/router/router.js
Isn't the best solution because didn't changed the URL but solved the problem.
> Prevent show incomplete view when is not incomplete

- src/Components/PdfEditor/PdfEditor.vue
> Temporary fix

- lib/Helper/JSActions.php
- src/Components/PdfEditor/PdfEditor.vue
- src/Components/Request/RequestSignature.vue
- src/Components/Request/VisibleElements.vue
- src/helpers/SelectAction.js
- src/views/Request.vue
- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
- tests/Unit/Controller/AEnvironmentPageAwareControllerTest.php
- tests/Unit/Middleware/InjectionMiddlewareTest.php
- tests/integration/features/account/create_to_sign.feature
- tests/integration/features/page/sign_identify_account.feature
- tests/integration/features/sign/request.feature
> Small UI fixes

- lib/AppInfo/Application.php
- lib/Middleware/GlobalInjectionMiddleware.php
- src/Components/File/AppFilesTab.vue
- src/Components/Request/RequestSignature.vue
- tests/psalm-baseline.xml
> Bugfixes app files

- Makefile
> Add composer folder to package

- appinfo/info.xml
> [stable28] Bump version

- lib/Controller/AdminController.php
- lib/Controller/AdminSseController.php
- lib/Service/InstallService.php
- src/views/Settings/DownloadBinaries.vue
> Improvements at download binaries

- lib/Service/ConfigureCheckService.php
- lib/Service/InstallService.php
- lib/Service/SignFileService.php
> Add support to arm64

- appinfo/info.xml
> [stable28]  Bump to release candidate 5

- lib/Service/SignerElementsService.php
- src/store/signatureElements.js
- src/views/Account/partials/Signatures.vue
- src/views/SignPDF/_partials/Sign.vue
> Check if signature exists to unauthenticated signer

- lib/Controller/IdentifyAccountController.php
This key only exist when is account, when is email the array does not have this value
> Prevent warning when search by email

- lib/Service/FileElementService.php
- package-lock.json
- package.json
- src/Components/Request/VisibleElements.vue
- src/views/SignPDF/SignPDF.vue
The signature position from VuePdfEditor consider that the upper Y is zero and JSignPdf consider that the lower Y is zero. LibreSign store the coordinates as JSignPdf pattern and was necessary convert to VuePdfEditor pattern.
> Signature position

- lib/Service/FileService.php
- src/Components/Moment.vue
- src/views/Validation.vue
API need to send epoch to use `@nextcloud/moment`
> Fix date format

- appinfo/info.xml
LibreCode is together and camel case
> Fix company name

- lib/Service/IdentifyMethod/Email.php
When I request to email a@a.a to sign a document
And before open the link to sing the document
Is created an account with the email a@a.a
The user need to be redirect to login page
> Redirect to login if user already exists

- appinfo/routes/routesFileController.php
- lib/Controller/FileController.php
- lib/Db/SignRequestMapper.php
- lib/Service/FileService.php
- src/Components/File/File.vue
- tests/psalm-baseline.xml
|Before|After|
|---|---|
|![Screenshot_20240304_155057](https://github.com/LibreSign/libresign/assets/1079143/bd9dd11e-0ee6-4860-afa4-be8902f42e03)|![Screenshot_20240304_155032](https://github.com/LibreSign/libresign/assets/1079143/2caca7a9-0ec1-403e-a5e8-93236770500d)|
> Generate thumbnail when is not my file

- src/Components/Request/VisibleElements.vue
> Remove selection of current file after request to sign

- src/store/files.js
- src/views/Timeline/Timeline.vue
> Fix filter

- src/views/Settings/Validation.vue
The current state is 0 or 1, not null. The previous code consider that the value could be null.
close #2430
> Use current state to validation url component

- src/Components/Request/RequestSignature.vue
- src/store/files.js
close: #2431
When authenticated with account **admin**:
|Before|After|
|---|---|
|![Screenshot_20240306_083048](https://github.com/LibreSign/libresign/assets/1079143/79af4349-8fc0-4e7f-9af8-150200931c95)|![Screenshot_20240306_121352](https://github.com/LibreSign/libresign/assets/1079143/8c15f7f1-6ef6-44ee-b229-06361825a5fd)|
> Add sign button when have more than one signer

- lib/Controller/PageController.php
- src/App.vue
- src/Components/Request/RequestSignature.vue
- src/router/router.js
- src/store/files.js
> Open sign in modal

- lib/Controller/PageController.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
When use UUID of signer and not of file, now will load the validation page
> Prevent redirect to error

- src/Components/Request/RequestSignature.vue
When the file already received a signature, the file need to be looked to changes.
> Remove add signers when cannot sav

- src/views/Account/Account.vue
|Before|After|
|---|---|
|![Screenshot_20240307_093944](https://github.com/LibreSign/libresign/assets/1079143/862e14a8-9269-4410-95ca-a3a2e6059beb)|![Screenshot_20240307_093729](https://github.com/LibreSign/libresign/assets/1079143/bb68383e-fc6f-4257-adbb-6c5dfd3b6858)|
> Improve layout of buttons at profile

- .github/workflows/behat.yml
- lib/Controller/IdentifyAccountController.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/identify-account/search.feature
- tests/integration/features/sign/request.feature
> [stable28] Return herself when search by email

- .github/workflows/behat.yml
- lib/Command/Configure/Cfssl.php
- lib/Command/Configure/OpenSsl.php
- lib/Controller/AccountController.php
- lib/Exception/EmptyCertificateException.php
- lib/Handler/CertificateEngine/AEngineHandler.php
- lib/Handler/CertificateEngine/CfsslHandler.php
- lib/Handler/CertificateEngine/IEngineHandler.php
- lib/Handler/CertificateEngine/OpenSslHandler.php
- lib/Handler/CfsslServerHandler.php
- lib/Handler/Pkcs12Handler.php
- lib/Service/AccountService.php
- lib/Service/InstallService.php
- lib/Service/SignFileService.php
- src/views/ReadCertificate.vue
- tests/Api/Controller/SignFileControllerTest.php
- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/features/account/signature.feature
- tests/integration/features/admin/certificate_openssl.feature
- tests/integration/features/bootstrap/FeatureContext.php
Example of certificate data generated by LibreSign:
> Fixes and tests coverage when generate CFSSL and OpenSSL root cert and PFX cert

- lib/Handler/Pkcs12Handler.php
- lib/Service/SignFileService.php
> Fix failure to sign with email

- lib/Middleware/InjectionMiddleware.php
The pdf package need javascript eval.
> Fix empty screen

- lib/Service/IdentifyMethod/SignatureMethod/Password.php
- src/views/SignPDF/_partials/Sign.vue
> Fix password field name

- lib/Helper/ValidateHelper.php
- lib/Service/SignFileService.php
The `profileElementId` was replaced by `profileFileId` and we havent more references to `profileElementId`
> Remove died code

- .github/workflows/behat.yml
- appinfo/routes/routesFileController.php
- lib/Command/Configure/Check.php
- lib/Controller/FileController.php
- lib/Service/AccountService.php
- lib/Service/FileService.php
- lib/Service/Install/ConfigureCheckService.php
- tests/integration/features/account/me.feature
> [stable28] Remove dead code

- composer.json
- composer.lock
This dependency is from server, not at app side
> Remove symfony console

- lib/Migration/Version8000Date20230420125331.php
- lib/Migration/Version8000Date20231102215331.php
The default is string and these columns are varchar, not integer
> fix: comlumn type

- src/Components/Request/RequestSignature.vue
- src/store/sign.js
- src/views/SignPDF/SignPDF.vue
Load file from storage or initial state and fix the structure of store
> fix: structure of array and store loading

- lib/Db/SignRequestMapper.php
The array $files is the root array, the array $data is added to signers array
> fix: array structure

- src/router/router.js
All other names are uppercase first
> chore: Convert route name to uppercase first

- appinfo/routes/routesPageController.php
- lib/Controller/PageController.php
- src/helpers/SelectAction.js
- src/router/router.js
> Incomplete route

- lib/Controller/PageController.php
> fix: Load incomplete page as internal and external page

- lib/Handler/CertificateEngine/AEngineHandler.php
- lib/Handler/CertificateEngine/CfsslHandler.php
- lib/Handler/CertificateEngine/OpenSslHandler.php
- lib/Handler/Pkcs12Handler.php
- lib/Handler/SignEngineHandler.php
- lib/Service/IdentifyMethod/SignatureMethod/Password.php
Reference:
- https://github.com/php/php-src/issues/12128
- https://www.php.net/manual/en/function.openssl-pkcs12-read.php#128992
> fix: Read legacy certificate

- src/views/Account/partials/Signature.vue
After edit or create, the signature preview need to be updated.
Removed reference to 'lodash-es'
> fix: refresh signature preview

- src/Components/RightSidebar/RightSidebar.vue
- src/views/Request.vue
Clean interface
|Before|After|
|---|---|
| ![Screenshot_20240412_123646](https://github.com/LibreSign/libresign/assets/1079143/65afbc01-ef67-4ef1-8f89-a55feb3e4ded) | ![Screenshot_20240412_123609](https://github.com/LibreSign/libresign/assets/1079143/0d0e9488-a29e-4824-9d1e-cf8c13f0aacb) |
> feat: hide buttons when file is chose

- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
> [stable29] feat: increase execution time of integration tests

- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
> [stable28] feat: increase execution time of integration tests

- src/Components/Draw/FileUpload.vue
|before|after|
|---|---|
|![Screenshot_20240418_081003](https://github.com/LibreSign/libresign/assets/1079143/bb4d0e0c-fc3c-44cb-b0c9-461eafa8fd5d)|![Screenshot_20240418_080503](https://github.com/LibreSign/libresign/assets/1079143/a471ea5b-6894-4984-a4a2-eb284541e576)|
> Fix css of vue advanced cropper

- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
- lib/Controller/AccountController.php
- lib/Service/AccountService.php
- lib/Service/FolderService.php
- lib/Service/SignFileService.php
- lib/Service/SignerElementsService.php
- lib/Service/TFile.php
- tests/Unit/Service/FolderServiceTest.php
- tests/integration/features/account/signature.feature
- tests/integration/features/bootstrap/FeatureContext.php
> [stable29] fix: save and retrieve file to guest account

- src/views/CreateAccount.vue
|Before|After|
|---|---|
|![Screenshot_20240423_111911](https://github.com/LibreSign/libresign/assets/1079143/50facf0a-f499-456c-9d23-004f8c3c4940)|![Screenshot_20240423_111851](https://github.com/LibreSign/libresign/assets/1079143/d4a20072-b30d-4948-8403-4f7437a6fd05)|
> fix: css at create account view

- src/views/ReadCertificate.vue
> fix(i18n): Fixed grammar

- composer.lock
> chore: bump dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> [stable29] feat: Changelog

- composer.json
Nextcloud apps don't need the removed properties
> chore: remove unsecessary composer properties

- composer.json
Use tab instead of spaces following the Nextcloud pattern
> chore: indent composer.json

- composer.json
- composer.lock
- vendor-bin/coding-standard/composer.json
- vendor-bin/coding-standard/composer.lock
- vendor-bin/php-coveralls/composer.json
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
> [stable28] chore: indent composer.json

- composer.json
- composer.lock
> [stable29] chore: indent composer.json

- src/Components/Request/VisibleElements.vue
Updates the text on the signature placement modal to better explain how to place a signature on any page.
Issue Number: 2903
Other: Text Change
> Update helper text on the modal to indicate usage on multi-page documents

- src/actions/openInLibreSignAction.js
close #2778
|PDF file| Non PDF file|
|---|---|
|![Screenshot_20240430_171331](https://github.com/LibreSign/libresign/assets/1079143/5ab0eb6d-6387-4bfd-9d38-4abd025aceee)|![Screenshot_20240430_171338](https://github.com/LibreSign/libresign/assets/1079143/98f283d8-2d7b-4e57-a288-177276f1b112)|
> feat: Move LibreSign to first position of app Files menu

- CONTRIBUTING.md
> I changed the text structure

- README.md
> I change the text format readme

- src/views/Settings/ExtraSettings.vue
- src/views/Settings/Settings.vue
At LibreSign Administration settings
> feat: Extra settings

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable28]  chore: changelog

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable29] chore: changelog

- package-lock.json
- package.json
> [stable29] chore(deps): Bump @nextcloud/files from 3.2.1 to 3.3.0

- src/views/IncompleteCertification.vue
This will redirect to settings/admin/libesign to finish the setup:
> feat: finish setup

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable28] chore: update changelog

- lib/Service/RequestSignatureService.php
- tests/Unit/Service/RequestSignatureServiceTest.php
> fix: prevent error when file extension is uppercase

- lib/Service/Install/InstallService.php
> fix: prevent to load the wrong java hash file

- lib/Service/FolderService.php
> fix: prevent error when delete visible signature file

- src/Components/Request/IdentifySigner.vue
|after|before|
|---|---|
|![Screenshot_20240531_125819](https://github.com/LibreSign/libresign/assets/1079143/d6e74b82-16f3-40a2-bf21-225d17bca77c)|![Screenshot_20240531_125853](https://github.com/LibreSign/libresign/assets/1079143/945c1c8b-4505-4867-b4f7-857ae106371c)|
> fix: select width

- lib/Service/Install/ConfigureCheckService.php
> fix: require java before test pdftk

- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- Makefile
> [stable29] chore: remove site API references from code

- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- Makefile
> [stable28] chore: remove site API references from code

- .github/workflows/appstore-build-publish.yml
- Makefile
> [stable28] Fix/build and publish

- .github/workflows/appstore-build-publish.yml
- Makefile
> [stable29] Fix/build and publish

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/BackgroundJob/UserDeleted.php
- lib/Db/File.php
- lib/Db/FileMapper.php
- lib/Db/IdentifyMethod.php
- lib/Db/IdentifyMethodMapper.php
- lib/Db/UserElement.php
- lib/Db/UserElementMapper.php
- lib/Listener/MailNotifyListener.php
- lib/Listener/NotificationListener.php
- lib/Listener/UserDeletedListener.php
- lib/Migration/Version10000Date20240625141149.php
- tests/Unit/Helper/ValidateHelperTest.php
Prevent to show files of deleted accounts when is created a new account with the same user id of deleted account.
> fix: neutralize deleted users

- src/views/SignPDF/_partials/Sign.vue
|🏚**Before**|🏡**After**|
|---|---|
|![Screenshot_20240625_150033](https://github.com/LibreSign/libresign/assets/1079143/2f87bb94-0101-44f2-bbf3-210423d0cc10)|![Screenshot_20240625_150037](https://github.com/LibreSign/libresign/assets/1079143/3f93e52d-6c19-4a1b-b5d2-a5046576d162)|
> chore: Disable sign button when is loading

- lib/Handler/JSignPdfHandler.php
|🏚**Before**|🏡**After**|
|---|---|
|![Screenshot_20240625_153526](https://github.com/LibreSign/libresign/assets/1079143/16993ba3-1204-4e03-98bd-871b5c07f368)|![Screenshot_20240625_153437](https://github.com/LibreSign/libresign/assets/1079143/a4e83904-c214-44a2-8dcf-b98a57e3b0b2)|
> fix: Make possible use multiple signatures of same signer

- .github/workflows/block-unconventional-commits.yml
- .github/workflows/dependabot-approve-merge.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node.yml
- .github/workflows/npm-audit-fix.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp-approve-merge.yml
- .github/workflows/update-nextcloud-ocp.yml
> [stable29] chore: update workflows

- .github/workflows/block-unconventional-commits.yml
- .github/workflows/dependabot-approve-merge.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node.yml
- .github/workflows/npm-audit-fix.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp-approve-merge.yml
- .github/workflows/update-nextcloud-ocp.yml
> [stable28] chore: update workflows

- appinfo/routes.php
- lib/Controller/AccountController.php
- lib/Controller/AdminController.php
- lib/Controller/DevelopController.php
- lib/Controller/FileController.php
- lib/Controller/FileElementController.php
- lib/Controller/IdentifyAccountController.php
- lib/Controller/NotifyController.php
- lib/Controller/PageController.php
- lib/Controller/RequestSignatureController.php
- lib/Controller/SettingController.php
- lib/Controller/SignFileController.php
- lib/Controller/SignatureElementsController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> [stable29] chore: move account routes definition to attributes

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable28] chore: changelog

- src/views/Request.vue
Add id to be more easy to found an unique element.
Add width to div to be a box and not a wide element
> chore: ui improvements

- package-lock.json
- package.json
Downgrade to compatible version
> fix: openapi dependencies

- Makefile
- lib/Command/Developer/SignSetup.php
- lib/Command/Install.php
- lib/Service/Install/InstallService.php
- lib/Service/Install/SignSetupService.php
- tests/Unit/Service/Install/SignSetupServiceTest.php
is necessary to consider the linux distribution when install java
> fix: Java setup

- .devcontainer/setup.sh
Devcontainer and CodeSpaces improvements to work with LibreSign app.
Issue Number: 3507
Improvements
> Add nextcloud config on devcontainer and CodeSpaces

- lib/Service/Install/SignSetupService.php
- tests/Unit/Service/Install/SignSetupServiceTest.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/build/sign.feature
> feat: Test signature proccess

- appinfo/info.xml
> chore: stable release

- lib/Listener/NotificationListener.php
- tests/integration/features/bootstrap/FeatureContext.php
> fix: open notification as internal url

- src/Components/RightSidebar/RequestSignatureTab.vue
- src/views/SignPDF/_partials/Sign.vue
ref: #3715
https://github.com/user-attachments/assets/5923e8d4-76fa-49fa-9ecf-deffe27dcc7a
> fix: close button

- lib/Controller/PageController.php
- src/views/Validation.vue
close #2885
https://github.com/user-attachments/assets/af4fec4c-f9e2-4c0d-bc67-1f4fddc03f79
> feat: use Viewer to open pdf

- .eslintrc.js
> [stable28] chore: convert indent size

- appinfo/info.xml
> chore(i18n); Fixed grammar

- appinfo/info.xml
> feat: add documentation url

- src/store/files.js
> fix: Use unicode signer name

- lib/Handler/CertificateEngine/CfsslHandler.php
- Remove the backtick operator https://www.php.net/manual/en/language.operators.execution.php
- Return more information when got error
- Validate if the command to check version return empty string
- Validate the output format of version command
- Return Runtime version
Related with: #3747
> chore: improve cfssl validation

- src/Components/Draw/Editor.vue
- src/Components/Draw/TextInput.vue
- src/Components/Request/IdentifySigner.vue
- src/views/CreateAccount.vue
- src/views/CreatePassword.vue
- src/views/FilesList/FilesList.vue
- src/views/ReadCertificate.vue
- src/views/Request.vue
- src/views/ResetPassword.vue
- src/views/Settings/CertificateCustonOptions.vue
- src/views/Settings/DefaultUserFolder.vue
- src/views/Settings/ExpirationRules.vue
- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
- src/views/Settings/Validation.vue
- src/views/SignPDF/_partials/ModalEmailManager.vue
- src/views/SignPDF/_partials/Sign.vue
- src/views/Validation.vue
Ref:
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5418/files
- https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.20.0
> chore: replace :value.sync by v-model

- src/views/Validation.vue
> fix: only show return when come from validation button

- lib/Service/SignFileService.php
Reference  #3660
This error could be a problem at PDFtk side
> chore: feedback improvement

- src/Components/Request/IdentifySigner.vue
|🏚 Before|🏡 After|
|---|---|
|![Screenshot_20241121_124610](https://github.com/user-attachments/assets/f8d1536a-205c-4f6a-9b79-536d82d4416c)|![Screenshot_20241121_124502](https://github.com/user-attachments/assets/03fe1376-de95-4c3a-b96c-001976634a0b) ![Screenshot_20241121_124529](https://github.com/user-attachments/assets/de75259f-7a8d-47b6-ab12-a91073a4c826)|
> feat: only show name and allow save signer when have signer

- src/Components/Signers/Signer.vue
The action buttons disappeared.
|---|---|
|![Screenshot_20241122_142750](https://github.com/user-attachments/assets/986f3448-aa9f-4de5-bdd9-3b9d56adda87)|![Screenshot_20241122_142719](https://github.com/user-attachments/assets/894f104e-67c4-4ff7-a8d7-131b3edfb0f6)|
> fix: show actions at signer list

- src/views/FilesList/FilesListTableFooter.vue
- src/views/FilesList/FilesListVirtual.vue
- src/views/FilesList/VirtualList.vue
> feat: add footer to file list

- src/Components/File/File.vue
> fix: JS error when upload file

- lib/AppInfo/Application.php
- lib/Listener/BeforeNodeDeletedListener.php
- src/Components/Request/VisibleElements.vue
- tests/Unit/Controller/AEnvironmentPageAwareControllerTest.php
When we delete the LibreSign folder and remove from trash, is necessary to delete LibreSign files too.
> fix: prevent don't delete file when folder is deleted

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Backport of https://github.com/LibreSign/libresign/pull/4083
> chore: changelog

- lib/Handler/FooterHandler.php
- lib/Service/SignFileService.php
> fix: footer in pages with different sizes

- lib/ResponseDefinitions.php
- lib/Service/FileService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
The signerid stay at $signer object.
> fix: load signature methods

- .github/workflows/psalm.yml
- lib/Service/Install/ConfigureCheckService.php
> [stable29] chore: implement logs

- src/Components/LeftSidebar/LeftSidebar.vue
- src/Components/Settings/Settings.vue
> feat: add rate LibreSign

- lib/Controller/FileController.php
- lib/Controller/PageController.php
- lib/Controller/RequestSignatureController.php
- lib/Service/FileService.php
FormatFile isn't a generic method name. The final objective of this method is to return an array structure of current class.
> chore: rename method

- lib/Handler/CertificateEngine/AEngineHandler.php
- lib/Handler/CertificateEngine/CfsslHandler.php
- lib/Handler/CertificateEngine/IEngineHandler.php
- lib/Handler/CertificateEngine/OpenSslHandler.php
- lib/Handler/CfsslServerHandler.php
- src/views/Settings/ExpirationRules.vue
- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
- src/views/Validation.vue
> feat: change expirity

- lib/Controller/PageController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
Added pending path
Issue: Returns 404 page for those who are not authenticated
Solution: Display the document to be signed for those who are not authenticated
> fix: path of renew url

- src/views/RenewEmail.vue
|---|---|
|![Screenshot_20250113_062631](https://github.com/user-attachments/assets/2bb426a5-4f67-4361-9388-35f6e3ca6097)|![Screenshot_20250113_062337](https://github.com/user-attachments/assets/b791465d-65b2-47e3-9841-fc175eec66b8)|
> fix: center component

- lib/Service/SessionService.php
> fix: method name

- lib/Controller/PageController.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
The method was renamed and the route also need to be renamed.
> fix: validation url

- src/helpers/fileStatus.js
> chore(i18n): Fixed grammar

- lib/Controller/AccountController.php
- lib/Handler/CertificateEngine/AEngineHandler.php
- lib/Handler/CertificateEngine/CfsslHandler.php
- lib/Handler/CertificateEngine/OpenSslHandler.php
- lib/Handler/CertificateEngine/OrderCertificatesTrait.php
- lib/Handler/Pkcs12Handler.php
- src/helpers/certification.js
- src/views/Account/partials/ManagePassword.vue
- src/views/ReadCertificate/CertificateContent.vue
- src/views/ReadCertificate/ReadCertificate.vue
- src/views/Settings/CertificateCustonOptions.vue
- tests/Unit/Handler/OpenSslHandlerTest.php
Now is possible see the "Certificate chain" when you follow the steps:
- Go to LibreSign app
- At down of left menu, click at "Settings"
- Generate or upload a cert if you haven't
- Click at "Read certificate"
- Type your certificate password
- Then you need to see "Certificate chain"
> feat: parse extracerts content

- lib/Controller/SignatureElementsController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> [stable29] fix: path of url

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable29] chore: update changelog

- Makefile
was replaced by LICENCES folder
> fix: remove licence file

- src/views/Settings/AllowedGroups.vue
> [stable29] fix: prevent error when enpty data from backend

- src/views/Settings/AllowedGroups.vue
> [stable31] fix: prevent error when enpty data from backend

- src/views/Settings/AllowedGroups.vue
> [stable30] fix: prevent error when enpty data from backend

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> [stable30] chore: changelog

- lib/Handler/CertificateEngine/CfsslHandler.php
Fixed:
Unable to connect to 127.0.0.1:8888 (Connection refused)
> fix: prevent warning of fsockopen

- lib/Handler/FooterHandler.php
- tests/Unit/Handler/FooterHandlerTest.php
> fix: use entities instead of char convertoing

- lib/Handler/FooterHandler.php
- tests/Unit/Handler/FooterHandlerTest.php
> fix: ltr language

- composer.json
- lib/Db/UserElement.php
- lib/Service/Install/SignSetupService.php
- psalm.xml
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
Without backport because php 8.1 only is the minimum version since server 32
> chore: bump psalm

- src/Components/Request/VisibleElements.vue
|🏚️ Before| 🏡 After|
|---|---|
|![Screenshot_20250224_133004](https://github.com/user-attachments/assets/bc87a64e-248e-4d4e-ac00-d4926fbc2197)|![Screenshot_20250224_133035](https://github.com/user-attachments/assets/a7a60414-a308-4a75-8df5-497fe85808d2)|
> feat: add information note about visible signature

- lib/Controller/AccountController.php
- lib/Controller/PageController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
I identified that the openapi documentation was outdated.
> chore: update openapi

- lib/Service/TFile.php
This started to throw error. I found this workaround at server side to fix this issue.
> fix: psalm issue

- tests/integration/features/identify-account/search.feature
The current search result isn't about account and not to email.
> fix: don't search by email

- src/Components/Draw/Editor.vue
- src/Components/Draw/FileUpload.vue
- src/Components/Draw/TextInput.vue
- src/Components/Request/IdentifySigner.vue
- src/Components/Request/RequestPicker.vue
- src/Components/Request/VisibleElements.vue
- src/Components/RightSidebar/RequestSignatureTab.vue
- src/Components/TopBar/SidebarToggle.vue
- src/views/Account/partials/UserImage.vue
- src/views/CreateAccount.vue
- src/views/CreatePassword.vue
- src/views/FilesList/FileEntry/FileEntryActions.vue
- src/views/FilesList/FileListFilters.vue
- src/views/FilesList/FilesListTableHeaderActions.vue
- src/views/FilesList/FilesListTableHeaderButton.vue
- src/views/ReadCertificate/ReadCertificate.vue
- src/views/RenewEmail.vue
- src/views/ResetPassword.vue
- src/views/Settings/DownloadBinaries.vue
- src/views/Settings/RootCertificateCfssl.vue
- src/views/Settings/RootCertificateOpenSsl.vue
- src/views/SignPDF/_partials/ModalEmailManager.vue
- src/views/SignPDF/_partials/Sign.vue
- src/views/Validation.vue
Follow up of:
https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.24.0
> chore: replace deprecated properties

- lib/Db/AccountFileMapper.php
- lib/Db/File.php
- lib/Db/SignRequest.php
- lib/Db/SignRequestMapper.php
- lib/Migration/Version12000Date20250325143340.php
- lib/Migration/Version12000Date20250325155910.php
- lib/Migration/Version12000Date20250325174734.php
- lib/ResponseDefinitions.php
- lib/Service/FileService.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/RequestSignatureService.php
- lib/Service/SignFileService.php
- openapi-full.json
- openapi.json
- src/store/files.js
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- src/views/FilesList/FileEntry/FileEntryMixin.js
- src/views/Validation.vue
- tests/Api/Controller/FileElementControllerTest.php
- tests/Api/Controller/SignFileControllerTest.php
- tests/Unit/Service/FileServiceTest.php
- tests/integration/features/sign/request.feature
> fix: time stamp when then document signed

- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- lib/Controller/LibresignTrait.php
- lib/Controller/PageController.php
- lib/Helper/ValidateHelper.php
- lib/Service/AccountService.php
- lib/Service/FileService.php
- lib/Service/FolderService.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/SignFileService.php
- tests/Unit/Helper/ValidateHelperTest.php
- tests/Unit/Service/AccountServiceTest.php
- tests/Unit/Service/SignFileServiceTest.php
> [stable29] fix: optimize file loading

- lib/Service/Install/InstallService.php
I only put a return inside the `if`, this remove the necessity of `else`.
> chore: remove unecessary else

- lib/Service/Install/ConfigureCheckService.php
Implemented lazy loading to reduce execution time of configure check.
Before: 0m6.300s
After: 0m3.256s
Related with:
- #4810
<details>
- After that, the terminal will show the build process.
- Wait until you see the message:  
```bash
✍️ LibreSign is up!
```
This may take a few minutes.
- Open the **Ports** tab (next to the **Terminal**).
- Look for the service running on port **80**.
- Hover over the …
> chore: reduce configure check time

- composer.lock
- tests/integration/composer.lock
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
> [stable30] chore: bump PHP dependencies

- src/Components/PdfEditor/PdfEditor.vue
This bug was added into the previous commit at this file.
> fix: send fileSrc to PDF Editor

- src/views/Validation.vue
|---|---|
|![Screenshot_20250513_181144](https://github.com/user-attachments/assets/476f04e8-76a8-4987-816b-d7f7b2a7d849)|![Screenshot_20250513_181258](https://github.com/user-attachments/assets/6e4725bb-15db-4293-b1a9-824368476715)|
> fix: css at validation page

- composer.lock
- tests/integration/composer.lock
- vendor-bin/coding-standard/composer.lock
- vendor-bin/openapi-extractor/composer.lock
- vendor-bin/php-coveralls/composer.lock
> [stable31] chore: bump PHP dependencies

- lib/Helper/ValidateHelper.php
- lib/Service/RequestSignatureService.php
- lib/Service/SignFileService.php
- tests/Unit/Helper/ValidateHelperTest.php
> chore: text improvement

- composer.lock
- vendor-bin/phpunit/composer.lock
> chore: bump PHP dependencies

- README.md
This pull request fixes the link for feature_request.yml in the README.md
> chore: Fix link in README.md to feature_request.yml form

- lib/Handler/CertificateEngine/CertificateHelper.php
- lib/Handler/CertificateEngine/OpenSslHandler.php
- lib/Service/Install/SignSetupService.php
- tests/php/Unit/Handler/CertificateEngine/CertificateHelperTest.php
- tests/php/Unit/Service/Install/SignSetupServiceTest.php
It's necessary to be possible reuse the methods and improve the test coverage.
> chore: start to move methods to Helper class

- lib/Handler/SignEngine/JSignPdfHandler.php
- lib/Helper/JavaHelper.php
- lib/Service/Install/ConfigureCheckService.php
- lib/Service/SignFileService.php
- tests/php/Unit/Handler/CertificateEngine/CertificateEngineFactoryTest.php
- tests/php/Unit/Handler/SignEngine/JSignPdfHandlerTest.php
- tests/php/Unit/Helper/JavaHelperTest.php
- tests/php/Unit/Service/SignFileServiceTest.php
Reference: https://github.com/LibreSign/libresign/issues/4872#issuecomment-2973041944
> fix: change lang environment when is possible

- src/Components/RightSidebar/RequestSignatureTab.vue
> chore: edit visible signatures

- lib/Controller/SignFileController.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/SignatureTextService.php
Reference: https://github.com/nextcloud/docker-ci/issues/790
> fix: replace heredoc by string concat

- composer.lock
- tests/integration/composer.lock
- vendor-bin/coding-standard/composer.lock
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
- vendor-bin/rector/composer.lock
> [stable30] chore: bump dependencies

- composer.lock
- tests/integration/composer.lock
- vendor-bin/coding-standard/composer.lock
- vendor-bin/php-coveralls/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
- vendor-bin/rector/composer.lock
> [stable31] chore: bump dependencies

- src/Components/RightSidebar/RequestSignatureTab.vue
- src/views/FilesList/FileEntry/FileEntryActions.vue
> feat:button open file

- lib/Helper/ValidateHelper.php
- lib/Migration/Version2040Date20211027183759.php
- lib/Service/AccountService.php
- lib/Service/FileService.php
- lib/Service/FolderService.php
- lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
- lib/Service/SignFileService.php
- tests/php/Unit/Helper/ValidateHelperTest.php
- tests/php/Unit/Service/AccountServiceTest.php
- tests/php/Unit/Service/SignFileServiceTest.php
The method getFirstNodeById was added at Nextcloud 29.
> chore: Replace getById by getFirstNodeById

- .github/workflows/phpunit-mysql.yml
The coverage was accidentally removed here:
https://github.com/LibreSign/libresign/commit/519e118a1118a356bed9b3050bd883a6c0d4f12b
> feat: add back coveralls

- .github/workflows/phpunit-mysql.yml
> fix: run coverage mode always

- .github/dependabot.yml
- .github/workflows/appstore-build-publish.yml
- .github/workflows/dependabot-approve-merge.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node.yml
- .github/workflows/npm-audit-fix.yml
- .github/workflows/openapi.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp-approve-merge.yml
- .github/workflows/update-nextcloud-ocp.yml
> [stable30] chore: update workflows

- .github/workflows/appstore-build-publish.yml
- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/openapi.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp.yml
- .github/workflows/update-psalm-baseline.yml
> [stable30] chore(deps): Bump shivammathur/setup-php from 2.30.0 to 2.35.3

- lib/Service/SignFileService.php
- tests/php/Unit/Service/SignFileServiceTest.php
To don't throw exceptions at the app file_version, we need to always return the owner of the file .signed.pdf.
- Bugfix
> fix: always return the owner of the file to be signed

- lib/Controller/SignatureElementsController.php
- lib/Middleware/InjectionMiddleware.php
- src/Components/PreviewSignature/PreviewSignature.vue
- src/store/signatureElements.js
- tests/integration/features/account/signature.feature
Available since Nextcloud 32
Reference:
https://github.com/nextcloud/server/blob/6c003eda5c1bf43bff6774d1b3362e5bb1c55111/lib/public/AppFramework/Http/Attribute/RequestHeader.php#L22
- Feature
> feat: add request header

- README.md
This PR adds a new **Contributors ✨** section at the end of the `README.md`.  
The section thanks all contributors and dynamically displays their avatars using [contrib.rocks](https://contrib.rocks).  
The contributors' image is also linked to the official GitHub contributors graph of the project.
Before:-
There is no contribution section in readme file.
After:-
Issue Number: Closes #5117  
- Documentation content changes
- [ x] Did you explain or provide a way of how can we test your code ?
- [ x] If your pull request is related to frontend modifications provide a print of before and after screen
- [ x] Did you provide a general summary of your changes ?
- [ x] Try to limit your pull request to one type, submit multiple pull requests if needed
- [x ] I implemented tests that cover my …
> update README.md - add Contributors section

- .github/pull_request_template.md
This PR updates the existing pull request template by adding a section at the end with detailed instructions on how to run LibreSign using GitHub Codespaces. This makes it easier for contributors and reviewers to quickly spin up and test the project without additional setup.
Issue Number: Closes #5140 
- Documentation content changes
- [ X] Did you explain or provide a way of how can we test your code ?
- [X ] Did you provide a general summary of your changes ?
- [ X] Try to limit your pull request to one type, submit multiple pull requests if needed
> Docs/add GitHub codespaces steps to pr template

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Backport of https://github.com/LibreSign/libresign/pull/5448
> [stable31] chore: changelog

- lib/Service/Install/ConfigureCheckService.php
Only a small improvement
- Refactoring (no functional changes, no api changes)
<details>
- After that, the terminal will show the build process.
- Wait until you see the message:  
```bash
✍️ LibreSign is up!
```
This may take a few minutes.
- Open the **Ports** tab (next to the **Terminal**).
- Look for the service running on port **80**.
- Hover over the URL and click the **globe icon** 🌐 to open it …
> chore: add link to logs

- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
> [stable32] fix: error at CI with PHP 8.3

- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
> [stable31] fix: error at CI with PHP 8.3

- .github/workflows/behat-mariadb.yml
- .github/workflows/behat-mysql.yml
- .github/workflows/behat-pgsql.yml
- .github/workflows/behat-sqlite.yml
> [stable31] fix: rollback previous commit

- .github/workflows/appstore-build-publish.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- Makefile
> [stable32] chore: update workflows

- lib/Service/ReminderService.php
- tests/php/Unit/Service/ReminderServiceTest.php
> [stable31] chore: cover with more scenarios
