LibreSign/libresign

src/views/Request.vue

If the function refers to the File application, the name should be changed to a capital letter.
Spelling unification in Transifex.

l10n: Change to a capital letter

---

lib/Controller/PageController.php
lib/Service/AccountService.php
tests/Unit/Controller/PageControllerTest.php

getPdf() should also return NOT_FOUND if the file aquired from the accounts-service is empty.

---

composer.json
composer.lock

backport of https://github.com/LibreSign/libresign/pull/809

[stable23] Bump endroid/qr-code from 4.4.8 to 4.4.9

---

composer.lock

backport of https://github.com/LibreSign/libresign/pull/891

[stable23] Bump tecnickcom/tcpdf from 6.4.4 to 6.5.0

---

Makefile
README.md
appinfo/info.xml
lib/Command/Configure/Check.php
lib/Handler/CfsslHandler.php
lib/Handler/Pkcs12Handler.php
lib/Service/AdminSignatureService.php
lib/Service/ConfigureCheckService.php

Add new command:
```
occ libresign:configure:check
```
Output:
```
Status Description
🟢      Can generate the preview                                                                           
🟢      Java version: OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)                               
🟢      Java binary: /var/www/html/data/appdata_oci5yur91drs/libresign/java-se-8u41-ri/bin/java            
🟢      JSignPdf version: 2.1.0                                                                            
🟢      JSignPdf path: /var/www/html/data/appdata_oci5yur91drs/libresign/jsignpdf-2.1.0/JSignPdf.jar       
🟢      LibreSign cli tools found in path: /var/www/html/data/appdata_oci5yur91drs/libresign/libresign-cli 
🟢      CFSSL: Version: 1.6.1, Runtime: go1.12.12
```
I don't know if …

Add new command to validate setup

---

README.md
appinfo/info.xml
appinfo/routes.php
lib/Controller/AdminController.php
lib/Handler/CfsslHandler.php
lib/Service/InstallService.php
lib/Service/PdfParserService.php
src/Components/File/File.vue
src/views/Request.vue
src/views/Settings/AdminFormLibresign.vue
src/views/Settings/AllowedGroups.vue
src/views/Settings/DownloadBinaries.vue
src/views/Settings/Settings.vue
src/views/Timeline/Timeline.spec.js
src/views/Timeline/Timeline.vue
tests/Api/Controller/AdminControllerTest.php

Download binaries from admin settings
Mark required fields
* cfsslUri & configPath isn't more required when using standalone files. Only is necessary to run a custom setup.
* Added button to download binaries
* Verify when load if all binaries were downloaded to identify if is necessary to enable download button

Download binaries from admin settings

---

lib/Command/Configure/Check.php
lib/Handler/CfsslHandler.php
lib/Helper/ConfigureCheckHelper.php
lib/Helper/MagicGetterSetterTrait.php
lib/Service/ConfigureCheckService.php
src/views/Settings/ConfigureCheck.vue
src/views/Settings/DownloadBinaries.vue
src/views/Settings/LegalInformation.vue
src/views/Settings/RootCertificate.vue
src/views/Settings/Settings.vue
tests/Unit/Helper/ConfigureCheckHelperTest.php

Refactor configure check response

---

appinfo/info.xml
lib/Migration/Version7000Date20221028022904.php

The migration [Version7000Date20221026003343](https://github.com/LibreSign/libresign/blob/main/lib/Migration/Version7000Date20221026003343.php#L51-L69) generated a wrong array to store the cert optional attibutes following this wrong format:
```json
{
"commonName": "Test Company",
"names": {
"C": "BR",
"O": "Organization",
"OU": "Organization Unit"
}
}
```
This migration is to convert from the exposed format to this format:
```json
{
"commonName": "Test Company",
"names": [
{
"id": "C",
"value": "BR"
},
{
"id": "O",
"value": "Organization"
},
{
"id": "OU",
"value": "Organization Unit"
}
]
}
```

Fix wrong migration

---

lib/Handler/CfsslHandler.php

Previously, an empty item was sent inside the names array when no names other than CN were set. This was making CFSSL API fail with an 400 BAD REQUEST response.
To reproduce the issue and verify the fix:
- Make sure you are in the main branch
- Regenerate the root certificate, setting the CN field only.
- Try to update your LibreSign password, it should fail.
- Switch to this branch and try to update the password again, it should succeed.

Fix newcert request when names array is empty

---

composer.json
composer.lock

After we moved the dev dependencies to a separated path, I identified the problem reported https://github.com/LibreSign/libresign/issues/1144 about:
```
Error: Class 'Symfony\Component\Console\Helper\TableCellStyle' not found in
/var/www/html/nextcloud/apps/libresign/lib/Command/Configure/Check.php:71
```
This dependency was added because the version of `symfony/console` of server is greater than the first version of this dependency that came with `TableCellStyle` class

Add dependency

---

appinfo/info.xml
lib/Service/InstallService.php

The page of project JSignPdf have a link to project Adoptium, because this I changed to this package and fixed the archtecture to intersection of architectures of Nextcloud Server allowed in info.xml architecture tag and architectures of Adoptium
https://jsignpdf.sourceforge.net/
Ref: https://github.com/LibreSign/libresign/issues/1170

Change the default java version

---

package.json

The previous constraint was allowing CI to run with a higher Node version (18). The fix is inspired by official Nextcloud apps. See https://github.com/nextcloud/deck/blob/33912454ae2b17dc3107e2e7b6145b42682fd078/package.json#L72

Fix Node engine version constraint in CI

---

package.json

[stable25] Fix Node engine version constraint in CI

---

Makefile

Remove cfssl directory from the published package, it was deleted back in #1132.
Additionally, use `npm ci` instead of `npm install`.

Fix makefile appstore target

---

lib/Controller/SignFileController.php
lib/Helper/ValidateHelper.php

If the flow of identification documents is enabled, the approvers need to have permission to sign an identification document if he haven't an identification document signed on our profile.
How to reproduce:
* Login with user A as admin
* Go to LibeSign admin settings
* Enable the __Identification documents__ flow
* Login with user B as common user
* As user B, go to LibreSign > settings > account and add an identification document
* As user A, go to LibreSign > Documents Validation and click to validate (sign) the identification document
* Then, the user A need to sign the identification document

Make possible to approvers can sign identification documents

---

lib/Command/Base.php
lib/Command/Configure/Cfssl.php
lib/Command/Install.php
lib/Command/Uninstall.php
lib/Service/InstallService.php
tests/Unit/Service/InstallServiceTest.php

Unlike the web application, Nextcloud Symfony console application does not log exceptions to the `nextcloud.log`. This is a change to help debugging some install errors from asynchronous CLI calls while we don't implement install logs in the admin page.

Log CLI exceptions

---

lib/Handler/Pkcs12Handler.php
lib/Service/AccountService.php

If have any problem at cert handler, don't make sense to display the button to generate password

Hide generate passowrd when cert handler isn't ok

---

lib/Service/ConfigureCheckService.php

The message about cfssl is related to root certificate and I put the reference in the text to be more easy to identify because we have the cfssl integration

Make the text more clear

---

lib/Service/AdminSignatureService.php

The frontend want to receive an object as the list of custom names of root certificate and when is before the first generation of root certificate, the list with custom names is empty and PHP return an array. With this change every time will send an object instead of array when is an empty list.

Fix generate root certificate at the first time

---

lib/Service/TFile.php
vendor-bin/coding-standard/composer.json
vendor-bin/coding-standard/composer.lock

The newest version of this package broked the CI because implemented a new pattern.

Lock friendsofphp/php-cs-fixer version

---

src/assets/styles/validation.scss

close #1459 
fix validation page in dark mode:

fix: layut signature validation in dark mode

---

lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
lib/Service/IdentifyMethod/Account.php
lib/Service/IdentifyMethod/Email.php
lib/Service/IdentifyMethodService.php
tests/integration/features/admin/initial_state.feature

Motivation: the appsetting `identify_methods` isn't manipulated by LibreSign when is defined, because this is necessary to verify the values when retrieve from database, sanitize and populate with the default values.
Added more tests and made necessary refactors to cover the scenarios.

Add more tests when save identify method

---

lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
lib/Service/IdentifyMethod/IIdentifyMethod.php
lib/Service/IdentifyMethodService.php

When we use OC::$server->get() will return the same instance all time and is necessary to return a new instance to don't override the previous instance.

Prevent override instance

---

.github/workflows/update-nextcloud-ocp.yml

The minimum version of PHP at Nextcloud server is 8.0 and if we run the command composer update in an environment with PHP 8.2 will update a lot of packages to versions that isn't compatible with PHP 8.0

Downgrade the PHP version to be compatible with Nextcloud server

---

lib/Middleware/InjectionMiddleware.php
tests/Unit/Middleware/InjectionMiddlewareTest.php
tests/psalm-baseline.xml

This change is to implement a middleware to handle errors and return the erros to client.
The client could be a request from API or a request made from user.
When the request have the header `Accept: 'application/json'` is made to API and will return as json
When the request haven't the header `Accept: 'application/json'` is made from user and will return as HTML with all properties of JSON as initial state
Suggestion of response from backend:
```yaml
openapi: "3.0.2"
info:
title: Response from routes
version: "1.0"
paths:
/test:
get:
responses:
200:
description: OK
content:
application/json:
schema:
type: object
allOf:
- type: object
properties:
action:
enum:
- 100
- 150
- 200
- 250
- 300
- 350
- 400
oneOf:
- type: object
description: Success
properties:
message:
type: string …
```

Cover afterException hook with tests

---

lib/Command/Configure/Cfssl.php
lib/Command/Configure/Check.php
lib/Command/Configure/OpenSsl.php
lib/Command/Developer/Reset.php
lib/Command/Install.php
lib/Command/Uninstall.php

- Named parameters on install command

Implement named parameters on all commands

---

lib/Command/Configure/Check.php
lib/Service/AccountService.php
lib/Service/ConfigureCheckService.php
lib/Service/FileService.php
tests/integration/features/account/me.feature

The default behavior is disabled.
To enable will be necessary run an `occ` command, but I think that we don't will need this code.

Disable page preview

---

lib/Controller/FileController.php
lib/Controller/PageController.php
lib/Controller/SignFileController.php
lib/Db/FileMapper.php
lib/Db/SignRequestMapper.php
lib/Helper/ValidateHelper.php
lib/Service/AccountService.php
lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
lib/Service/IdentifyMethod/Account.php
lib/Service/IdentifyMethod/Email.php
lib/Service/SignFileService.php
src/App.vue
src/Components/Request/VisibleElements.vue
src/helpers/SelectAction.js
src/router/index.js
src/router/router.js
src/store/index.js
src/views/DefaultPageSuccess.vue
src/views/SignPDF/SignPDF.vue
src/views/Timeline/Timeline.vue
tests/integration/features/account/create_to_sign.feature
tests/integration/features/page/sign_identify_account.feature
tests/integration/features/page/validate.feature

I separated the content of complex methods in specific initial state values.
Making this I identified code executions that wasn't necessary. As example, the endpoint to display page to reset password.

Organize initial states

---

composer.json

This is very bad because every time when we need only to install a package, the update script was executed updating packages that I don't want to update. I removed this.

Disable execution of composer update every when install a new package

---

src/router/router.js

Normally the parameter is the UUID, if we don't send to the next route the url will be changed to default houte because don't will match the path or url.

Send params to next route

---

src/Components/Request/RequestSignature.vue

* The file is signed when sign_date is filled. In this case, don't make sense to send a reminder to sign
* When the user can't reques to sign, is disallow to send reminder
|Before|After|
|---|---|
| ![image](https://github.com/LibreSign/libresign/assets/1079143/ce2d375b-6829-4824-84c6-da2d6dcf5346) | ![image](https://github.com/LibreSign/libresign/assets/1079143/f8bd0877-165c-4f13-b60f-51c162bffff5) |
|Before|After|
|---|---|
| ![image](https://github.com/LibreSign/libresign/assets/1079143/a34f7403-2ff7-441c-b86c-f5a6fa10148f) | ![Screenshot_20240106_142148](https://github.com/LibreSign/libresign/assets/1079143/7446515d-1a47-4411-a2fa-fed229842f71) |
|Before|After|
|---|---|
| ![Screenshot_20240106_142148](https://github.com/LibreSign/libresign/assets/1079143/7446515d-1a47-4411-a2fa-fed229 …

Hide unauthorized actions and add validation action

---

lib/Controller/NotifyController.php

If we catch LibreSign Exception as the way of this code, will put the json settings of LibreSignException inside the message place.

Handle LibreSign exception

---

lib/Service/SignFileService.php
tests/Unit/Service/SignFileServiceTest.php

Problem: Nextcloud server disalowed to write a content into a file that isn't of authenticated user.
Workaround: to prevent error when try to save a file in a folder of different authenticated user
At the follow code:
https://github.com/nextcloud/server/blob/4173dfe05bd0155eb217dd428ac82091a508567a/apps/files_versions/lib/Listener/FileEventsListener.php#L350-L366 Nextcloud server force to use the user folder to get the file of authenticated user. This piece of code is to bypass the logic to use the authenticated user.
We need to identify a way to be possible save the file content

Make possible save a file content into a file of different authenticated user

---

lib/Service/TFile.php
src/views/Request.vue

When the URL is invalid or we got an error sever side, this error now is displayed to user
Only to do a best explain about this screenshot:
- I got the error because I'm running PHP as FPM and haven't localhost domain. The http server at my environment stay running at a separated machine

Add feedback when got error server side

---

src/views/Request.vue

Fix error on close modal

---

lib/Service/InstallService.php

We only need to do a return if the process isn't running

If we do a return, dont will check other proccess

---

webpack.config.js

When we create a signature by typing a text, use a font that need to be loaded by webpack

Fix load font

---

lib/Service/FileService.php

The method always return an array, don't need to check if exists. The return need to always return the array of visible elements.

Prevent warning when do not have visible elements

---

src/Components/Request/RequestSignature.vue

When we request to sign a file, this property does not exists. This property only exists after request to sign

Fix check if requested_by exists

---

src/Components/Request/VisibleElements.vue

The loading need to be defined to false after all API request

Prevent to don't close modal when API return an error

---

src/Components/Request/RequestSignature.vue

This is about the notification that is send to all signers by email or by Nextcloud notification
Now, the notification is send when click on request

Disable notification when click on next

---

lib/Db/SignRequestMapper.php

If we use cache, when we get data of a signer, the cache is populate with this signer. When we try to get all signers, the cacke don't work fine because will return the first signer.
Removed the cache.

Fix update signer

---

tests/integration/features/account/create_to_sign.feature

Running the tests locally I identified this problem at scenario. Maybe because my environment is dirty. To prevent future errors, I implemented steps to clean the environment before run tests.

Fix error that occurr locally

---

lib/Db/SignRequestMapper.php

The previous order removed the columns to be returned

Fix column order

---

lib/Service/FolderService.php
tests/Unit/Service/FolderServiceTest.php

close: #2433
If the authenticated account is member of group `guest_app`, will create the `pfx` file and the signature element (image of signature) at folder:
```
data/appdata_ockfwjh4mojn/libresign/guest_app/guest@a.a/signature.pfx
```

Make compatible with app guests

---

lib/Controller/AdminController.php
lib/Service/InstallService.php

When the download progress is removed, all errors is removed together, we need to check first if exist errors on return of process, if yes we can't remove the download progress because the method to get errors will clean all.

Prevent hide validate setup errors

---

appinfo/info.xml
appinfo/routes/routesNotifyController.php
lib/Activity/FileToSign.php
lib/Activity/Filter.php
lib/Activity/Listener.php
lib/Activity/Provider/SignRequest.php
lib/AppInfo/Application.php
lib/Command/Developer/Reset.php
lib/Controller/NotifyController.php
lib/Listener/MailNotifyListener.php
lib/Listener/NotificationListener.php
lib/Notification/Notifier.php
lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
lib/Service/IdentifyMethod/Account.php
lib/Service/IdentifyMethod/Email.php
lib/Service/IdentifyMethod/IIdentifyMethod.php
lib/Service/IdentifyMethod/IdentifyMethodService.php
lib/Service/NotifyService.php
lib/Service/RequestSignatureService.php
tests/integration/composer.json
tests/integration/composer.lock
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/page/sign_identify_account.feature
tests/integration/features/sign/request.feature
tests/psalm-baseline.xml

Close #2425
If disabled at Activity app, don't will be send.
If Activity app is not installed, will be send.
This email is send independent of LibreSign. If you don't want that this email be send, disable at Activity app.

Implement filter at Activity

---

.github/workflows/behat.yml
lib/Controller/AccountController.php
lib/Exception/EmptyCertificateException.php
lib/Handler/CertificateEngine/AEngineHandler.php
lib/Handler/CertificateEngine/CfsslHandler.php
lib/Handler/CertificateEngine/IEngineHandler.php
lib/Handler/CertificateEngine/OpenSslHandler.php
lib/Handler/CfsslServerHandler.php
lib/Handler/Pkcs12Handler.php
lib/Service/AccountService.php
lib/Service/InstallService.php
lib/Service/SignFileService.php
src/views/ReadCertificate.vue
tests/Api/Controller/SignFileControllerTest.php
tests/integration/composer.json
tests/integration/composer.lock
tests/integration/features/account/signature.feature
tests/integration/features/admin/certificate_openssl.feature
tests/integration/features/bootstrap/FeatureContext.php

[stable28] Fixes and tests coverage when generate CFSSL and OpenSSL root cert and PFX cert

---

lib/Handler/CertificateEngine/AEngineHandler.php
lib/Handler/CertificateEngine/IEngineHandler.php
lib/Migration/Version7000Date20221026003343.php
tests/Unit/Handler/OpenSslHandlerTest.php
tests/Unit/Service/InstallServiceTest.php
tests/Unit/TestCase.php
tests/integration/composer.lock
tests/integration/features/account/signature.feature

Implement tests

---

composer.json
composer.lock
lib/Db/File.php
lib/Db/SignRequest.php
lib/Db/SignRequestMapper.php
lib/Handler/Pkcs12Handler.php
lib/Handler/TCPDFLibresign.php
lib/Service/FileElementService.php
lib/Service/FileService.php
lib/Service/SignFileService.php
tests/Unit/Handler/Pkcs12HandlerTest.php

TCPDI have problems when manipulate the original PDF file. The approach to add footer at PDF files was replaced by create an overlay to each page and merge with original PDF file.

Replace TCPDI by TCPDF

---

lib/Service/PdfParserService.php

I identified an edge case parsing a PDF generated with FPDF. The MediaBox don't exists at page scope and was necessary to get from document scope.

fix: make compatible with FPDF

---

src/views/ReadCertificate.vue

* Replaced dialog by NoteCard
* Fix error handler
Message on error:

fix: handle error message when read certificate

---

lib/Controller/AccountController.php

The non unicode chars throw error at function json_encode when convert the array data to send as json at body of response

fix: remove non unicode chars when read certificate data

---

src/views/ReadCertificate.vue

The certificate data, password, error message need to be empty when modal is open. I also put this to close function to prevent to have these data when is no more necessary.
I also converted the modal to large when display the certificate data because in some cases, the certificate data have very large rows and a lot of rows.

chore: reset modal when load and close

---

.github/workflows/behat-mariadb.yml
.github/workflows/behat-mysql.yml
.github/workflows/behat-pgsql.yml
.github/workflows/behat-sqlite.yml
lib/Controller/AccountController.php
lib/Service/AccountService.php
lib/Service/FolderService.php
lib/Service/SignFileService.php
lib/Service/SignerElementsService.php
lib/Service/TFile.php
tests/Unit/Service/FolderServiceTest.php
tests/integration/features/account/signature.feature
tests/integration/features/bootstrap/FeatureContext.php

[stable28] fix: save and retrieve file to guest account

---

lib/Service/SignFileService.php

When we collect the user metadata to save on the time that the document is signed, is necessary to merge with previous metadata.

fix: merge metadata

---

src/views/Account/partials/Signature.vue

Is necessary to await the API response before display the answer of API. The request to API is made asynchronous,

fix: await api response

---

lib/Service/FileService.php

This method is used inside a loop on siner list of a document and is necessary to retunr only the visible elements of current signer, not of all signers of document.

fix: return the current signer box

---

lib/Service/Install/InstallService.php

Fixing the check on regular expression matches. The named group is <version> not <ID> therefore the field have to be $matches['version'] to make a correct check
https://github.com/LibreSign/libresign/pull/3049
- Bugfix
Now testing the modifications on InstallService.php with the two commits and with the change of this pull request the branch of fix/check-if-is-alpine will work well with Nextcloud-AIO / Alpine based Nextcloud - If the distribution is not containing "alpine" the fix does not interfere with any other installations.

Wrong identifier on new distribution check (Successfully tested on Nextcloud-AIO)

---

lib/Service/Install/InstallService.php

This is necessary to download specific Java package to Alpine.
Reference:
- #3026

fix: check if is alpine

---

lib/Service/FolderService.php

When we do a sync of a folder created with two points using Nextcloud desktop client, Windows don't recognize this and will do an error.

fix: prevent error when synchonize with windows

---

tests/Api/ApiRequester.php
tests/Api/Controller/AdminControllerTest.php
tests/Unit/Handler/OpenSslHandlerTest.php
tests/Unit/Service/InstallServiceTest.php

Issue Number: #2972
- Other (please describe): Improvements - updating the namespace of vfsStream class used for tests
Before the update:
Tests: 196, Assertions: 154, Errors: 85, Failures: 1, Skipped: 10.
After the update:
Tests: 196, Assertions: 216, Errors: 25, Failures: 1, Skipped: 16.

fix: update namespace of vfsStream class on tests

---

src/Components/Draw/Draw.vue

The NcModal component (maybe) have a media problem that broke the height of our Draw component. I made a workaround to fix this.

fix: draw width

---

lib/Controller/SignatureElementsController.php

The plural function of Nextcloud only work fine to identify if is singular or plural if the text contains a placeholder with a modifier. Only using a count to identify if is singular or plural, don't woks fine.

fix: prevent duplicate text

---

lib/Service/AccountService.php

fix: prevent warning when check if array has key

---

composer.json
composer.lock
lib/Handler/FooterHandler.php
lib/Handler/Templates/footer.php
psalm.xml
tests/Unit/Handler/FooterHandlerTest.php
tests/psalm-baseline.xml

close https://github.com/LibreSign/libresign/issues/3795

fix: open settings together with cms_pico

---

.github/workflows/owasp-dependency-check.yml

Will be necessary check if is possible:
- https://github.com/LibreSign/libresign/pull/3832
Sounds that this action do the same as dependabot but dependabot have a best result. Maybe we don't need to merge this PR.

feat: add OWASP dependency check

---

lib/Handler/FooterHandler.php
lib/Handler/Templates/footer.php
tests/Unit/Handler/FooterHandlerTest.php

fix: add back the contition to write_qrcode_on_footer

---

src/store/files.js

When already loaded all files, filter existing files using the filter argument when this exists

fix: filter files by signer uuid

---

lib/Service/FileService.php

Maybe the file was deleted and at this moment we don't want to receive an error if the file was not found

fix: go ahead if the file is not found

---

src/store/files.js

Without an unique ID, when do a delete will delete all that haven't an unique ID. By this way we assure that all will have an unique id

fix: assure that all signers will have an unique id

---

lib/Controller/PageController.php
src/helpers/SelectAction.js
src/router/router.js
src/views/DefaultPageError.vue

Now we already don't send data to validation page when the public access to this route is blocked but we follow loading the frontend without data. With this change will redirect to an error page

fix: block access to route when isn't allowed by admin

---

src/views/FilesList/FilesList.vue
src/views/FilesList/FilesListTableFooter.vue
src/views/FilesList/FilesListTableHeader.vue

If we have files and apply a filter that will return an empty list of files, is necessary to show the footer with "0 files".

fix: consider filter status to toggle components

---

lib/Activity/Listener.php
lib/Activity/Provider/SignRequest.php
lib/Notification/Notifier.php

since 30.0.0:
Providers should throw `UnknownActivityException` instead of `\InvalidArgumentException` when they did not handle the event. Throwing `\InvalidArgumentException` directly is deprecated and will be logged as an error in Nextcloud 39.

fix: change error class

---

.github/workflows/psalm.yml
lib/Service/Install/ConfigureCheckService.php

chore: implement logs

---

.github/workflows/psalm.yml
lib/Service/Install/ConfigureCheckService.php

[stable30] chore: implement logs

---

src/Components/Request/RequestPicker.vue

When upload a file, the extension is removed to don't have a document called `file.pdf.pdf`
Maybe will be necessary do the same at backend side.

fix: remove extension from filename

---

lib/ResponseDefinitions.php
lib/Service/IdentifyMethodService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

When we make a patch at a signature request, the signature method need to be always returned and this continue was removing the signature methods from return object.
Side effects of previous code: When I make a patch of herself sign request, I can't sign the document if the file list wasn't updated because the signature methods is returned to each element when we are listing the files. With this change is possible to return the signature methods after I'm added to be a signer and go ahead to sign the document.

fix: fetch signature methods

---

lib/Handler/JSignPdfHandler.php
lib/ResponseDefinitions.php
lib/Service/IdentifyMethodService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
src/views/Settings/Settings.vue
src/views/Settings/SignatureHashAlgorithm.vue
src/views/SignPDF/_partials/Sign.vue

The default hash algorithm of JSignPdf is SHA1 and with this change was defined SHA256 as default hash algorithm and make possible choose between the allowed algorithms: SHA1, SHA256, SHA384, SHA512, RIPEMD160.
Follow the compatibility analysis with different algorithms of documents signed by LibreSign. The follow analysis was made at https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation
|SHA1 :red_circle:  |SHA256 :green_circle: |RIPEMD160 :red_circle: |
|---|---|---|
|![Screenshot_20241223_205949](https://github.com/user-attachments/assets/3607d27a-9cb0-4042-8183-eae99631bd1c)|![Screenshot_20241223_205936](https://github.com/user-attachments/assets/2f44d5f8-46f4-4506-9082-3dc48bb023da)|![Screenshot_20241224_001655](https://github.com/user-attachments/assets/4fe5ac2d-d47 …

feat: allow to change signature hash algorithm

---

lib/Controller/AccountController.php
lib/Controller/FileController.php
lib/Controller/SignFileController.php
lib/Handler/CertificateEngine/AEngineHandler.php
lib/Handler/CertificateEngine/CfsslHandler.php
lib/Handler/CertificateEngine/IEngineHandler.php
lib/Handler/CertificateEngine/OpenSslHandler.php
lib/Handler/Pkcs12Handler.php
lib/Helper/MagicGetterSetterTrait.php
lib/Service/AccountService.php
lib/Service/FileService.php
lib/Service/SignFileService.php
src/views/CreatePassword.vue
src/views/Validation.vue
tests/Api/Controller/SignFileControllerTest.php
tests/Unit/Handler/Pkcs12HandlerTest.php
tests/integration/features/account/signature.feature

|---|---|
|![Screenshot_20241230_214816](https://github.com/user-attachments/assets/a66b36bc-188a-4f81-8a1a-c182275dc04d)|![Screenshot_20241230_214617](https://github.com/user-attachments/assets/bc84feea-3c1c-4fcf-8554-a31030d84b8c)|

feat: validate pdf

---

lib/Service/IdentifyMethod/AbstractIdentifyMethod.php

The previous commit used the wrong method name, is necessary to be get and not set at this place.

fix: method name

---

lib/Listener/MailNotifyListener.php

When the user is not authenticated, is necessary to send notification by email after renew the duration of sign request
Steps to reproduce:
- At Administration Settings > LibreSign
- Enable email as identification method
- set renewal interval to 5 seconds
- Send a sign request to an email that haven't any account associated
- Access the link received by email after 5 seconds
- Click at the button to renew the sign link
Expected behavior:
- You need to receive an email
Behavior before fix:
- The email wasn't sent

fix: notify by email when is not authenticated

---

src/Components/RightSidebar/SignTab.vue

After sign with unauthenticated signer, the validation page need to be the external.

fix: prevent js error

---

src/store/files.js

At listing of sign request immediately after then is uploaded a file to request a new signature, the frontend iterate at signers array but signers wasn't initialized at this moment.
Was added a check preventing access to undefined property.

fix: prevent error when add new signer

---

lib/Migration/Version11000Date20250114182030.php
lib/Migration/Version8000Date20230420125331.php

When was published the biggest release 8 of LibreSign, was made a mistake and the column name was changed causing inconsistent data at old registers.
Because haven't backup of old data, I made a workaround to restore the possible data considering that at migration Version8000Date20230420125331.php the field `signed` was used to fill identified_at_date and last_attempt_date.
This fix only will affect the problematic rows.

fix: migration column

---

webpack.config.js

This will split in smaller bundles

fix: prevent kill webpack

---

src/Components/Request/RequestPicker.vue
src/views/CreatePassword.vue
src/views/ReadCertificate.vue
src/views/ResetPassword.vue
src/views/SignPDF/_partials/Sign.vue

At previous change was added the native type equals to submit to all buttons, but at some buttons the click action stopped to work. The click action was added again.

fix: submit on click

---

lib/Controller/SignatureElementsController.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

fix: path of url

---

src/App.vue
src/helpers/SelectAction.js
src/router/router.js

To display an error is necessary to be displayed at the same route. The previous behavior was changing the path and generating strange side effects.

fix: display error at same route

---

lib/Service/Install/InstallService.php
tests/Unit/Service/InstallServiceTest.php

If we have a path /libresign/path/of/folder, all floders need to be exists when we send this to save the downloaded file.

fix: prevent generate a path without existing folder

---

lib/Handler/JSignPdfHandler.php
lib/Service/Install/ConfigureCheckService.php
lib/Service/Install/InstallService.php

All versions of dependencies stays at InstallService, because this the version of JSignPdf also was moved to this class.

refactor: moved version of JSignPdf to InstallService

---

tests/integration/features/identify-account/search.feature

chore: tests improvement

---

lib/Handler/FooterHandler.php

See: https://www.php.net/mb_convert_encoding#refsect1-function.mb-convert-encoding-changelog

chore: replace deprecated function

---

lib/Service/SignFileService.php
tests/Unit/Service/SignFileServiceTest.php

If the metadata field of a sign request is null, the array_merge function will throws an error because wait for an array as argument.
I also identified after implement the tests that when exists a previous value and this value is changed, the order of array_merge was prioritizing the previous value and the new value never was saved. I flipped the arguments of array_merge to prevent this.

fix: prevent error when collect metadata

---

lib/Handler/JSignPdfHandler.php
tests/Unit/Handler/JSignPdfHandlerTest.php

Was identified scenarios that could generate error and because this the getJSignPdf methdo was changed to cover more possible scenarios.

chore: cover jsignparam with tests

---

lib/Handler/Pkcs12Handler.php

ref: https://github.com/LibreSign/libresign/issues/4770#issuecomment-2790224178

fix: prevent error when output of pdfsig is empty

---

.github/workflows/behat-mariadb.yml
.github/workflows/behat-mysql.yml
.github/workflows/behat-pgsql.yml
.github/workflows/behat-sqlite.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
lib/Controller/LibresignTrait.php
lib/Controller/PageController.php
lib/Helper/ValidateHelper.php
lib/Service/AccountService.php
lib/Service/FileService.php
lib/Service/FolderService.php
lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
lib/Service/SignFileService.php
tests/Unit/Helper/ValidateHelperTest.php
tests/Unit/Service/AccountServiceTest.php
tests/Unit/Service/SignFileServiceTest.php

When load a file, we have the owner, this optimize the file loading preventing to search by nodeId at all places

fix: optimize file loading

---

lib/Helper/ValidateHelper.php
lib/Service/AccountService.php
lib/Service/FileService.php
lib/Service/FolderService.php
lib/Service/IdentifyMethod/IdentifyService.php
lib/Service/SignFileService.php
tests/Unit/Helper/ValidateHelperTest.php
tests/Unit/Service/AccountServiceTest.php
tests/Unit/Service/FileServiceTest.php
tests/Unit/Service/FolderServiceTest.php
tests/Unit/Service/SignFileServiceTest.php

Every when we load a file from Nextcloud, would be good to have the fileId to be quicky. When we request to sign a file from fileId, the file already exists before create the sign request and because this, we haven't a LibreSign file. To prevent error, I get the userId of who requessted to sign the document and sent to validation methods and after whis, was possible to validate the file.
close #4847

fix: user userId when validate file

---

COPYING

After we implemented the folder LICENSES, we made a wrong remotion of main license file of this repository that was added again at file COPYNG

fix: main license file

---

lib/Service/Install/InstallService.php

chore: bump java version

---

lib/Service/Install/ConfigureCheckService.php

This will give a best feedback to developers when the signature of dependencies is invalid.
Reference:
- #4810

chore: improve feedback of configure check

---

lib/Service/SignFileService.php
tests/Unit/Service/SignFileServiceTest.php

Previous logic:
- Try to create the file using full path at root folder
- Save the file content at created file.
Problem: Nextcloud server disalowed to write a content into a file that isn't of authenticated user because will use the authenticated user to handle root folder.
Current logic:
- Get the parent nodeId of original file. This is the folder of original file.
- Get the owner of original file
- Get the user folder of onwer
- Using the nodeId from first step, get the parent folder by ID
- Create the signed file inside the parent folder
Possible solution: When we get the user folder of owner of file, will get with permission to write.

chore: change save signed file logic

---

composer.lock
tests/integration/composer.lock
vendor-bin/coding-standard/composer.lock
vendor-bin/openapi-extractor/composer.lock
vendor-bin/php-coveralls/composer.lock

Will be necessary create the backport handmade after merge this PR to stables 31 and 30.
This was necessary to update Nextcloud OCP.
We have an action to do this (automatically update Nexcloud OCP package) but wasn't working fine and because this sometimes we need to do this handmade.
After merge this, also will be necessary run at server path a  `git pull origin master`

chore: bump PHP dependencies

---

src/Components/Settings/Settings.vue

Added link to administration settings at settings menu:
|---|---|
|![Screenshot_20250513_150916](https://github.com/user-attachments/assets/1ac2e7c2-24ae-4ae7-8fc5-fb3f165ee6a2)|![Screenshot_20250513_150604](https://github.com/user-attachments/assets/40fb954f-7ed5-4136-97b6-9b1737cf52bf)|
This don't will open administration settings as modal, this use the href attribute.

feat: add administration settings to settings menu

---

lib/Controller/AdminController.php
lib/Controller/CertificatePolicyController.php
lib/Handler/CertificateEngine/AEngineHandler.php
lib/Handler/CertificateEngine/CfsslHandler.php
lib/Handler/CertificateEngine/OpenSslHandler.php
lib/Handler/CfsslServerHandler.php
lib/ResponseDefinitions.php
lib/Service/CertificatePolicyService.php
lib/Settings/Admin.php
openapi-administration.json
openapi-full.json
openapi.json
src/types/openapi/openapi-administration.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
src/views/Settings/CertificatePolicy.vue
src/views/Settings/RootCertificateCfssl.vue
src/views/Settings/RootCertificateOpenSsl.vue
src/views/Settings/Settings.vue
tests/Unit/Handler/CertificateEngine/OpenSslHandlerTest.php
tests/Unit/Handler/SignEngine/JSignPdfHandlerTest.php
tests/Unit/Service/CertificatePolicyServiceTest.php
tests/Unit/Settings/AdminTest.php
tests/lib/AppConfigOverwrite.php

At `Administration Settings > LibreSign`
Before generate certificate:
After generate certificate:
Reading certificate data is possible to see the certificate policies at owner and issuer certificate:
<details>
- Go to the branch: [feat/manage-certificate-policy](https://github.com/LibreSign/libresign/tree/feat/manage-certificate-policy)
- After that, the terminal will show the build process.
- Wait until you see the message:  
```bash
✍️ LibreSign is up!
```
This may take a few minutes.
- Open the **Ports** tab (next to the …

feat: manage certificate policy

---

lib/Handler/SignEngine/JSignPdfHandler.php
tests/Unit/Handler/SignEngine/JSignPdfHandlerTest.php

When the signature stamp is SIGNAME_AND_DESCRIPTION or DESCRIPTION_ONLY, the signer don't will have a personal signature stamp.

fix: prevent merge when haven't a signature

---

appinfo/info.xml
lib/Activity/Filter.php
lib/Activity/Listener.php
lib/Activity/Provider/SignRequest.php
lib/Activity/Provider/Signed.php
lib/Activity/Settings/FileSigned.php
lib/Activity/Settings/FileToSign.php
lib/AppInfo/Application.php
lib/Controller/NotifyController.php
lib/Events/ASignedCallbackEvent.php
lib/Events/SendSignNotificationEvent.php
lib/Events/SignedCallbackEvent.php
lib/Events/SignedEvent.php
lib/Listener/MailNotifyListener.php
lib/Listener/NotificationListener.php
lib/Listener/SignedCallbackListener.php
lib/Listener/SignedListener.php
lib/Migration/Version12000Date20250517134200.php
lib/Notification/Notifier.php
lib/Service/Install/InstallService.php
lib/Service/MailService.php
lib/Service/NotifyService.php
lib/Service/SignFileService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/Unit/Activity/FileSignedTest.php
tests/integration/features/sign/request.feature
tests/integration/features/sign/signed.feature

Activity Settings Page:
Issue Number: https://github.com/LibreSign/libresign/issues/2618
- Feature

feat: adding new activity configuration

---

lib/Service/IdentifyMethod/Email.php
tests/Unit/Service/IdentifyMethod/EmailTest.php

When we try to validate by email and the validation by email is disabled, need to throw an error.

fix: throw error when identify by email is disabled

---

lib/Activity/Listener.php
lib/Activity/Provider/Signed.php
lib/Activity/Settings/FileSigned.php
lib/Listener/NotificationListener.php
lib/Notification/Notifier.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/sign/signed.feature

When the signer haven't an account, also is necessary to notify who requested to sign the file.
- Added: Signer representing the item of identify method
- Renamed: signed-file to sign-request, the new name is more clear
Solve:
- #5011

fix: notification and activity parameters

---

tests/integration/features/sign/request.feature

I increased the renewal interval to be bigger than a possible delay at a request.

fix: prevent flakiness at scenario with time

---

lib/Handler/SignEngine/JSignPdfHandler.php
lib/Service/Install/InstallService.php
tests/php/Unit/Handler/SignEngine/JSignPdfHandlerTest.php

JSignPdf request a config file but this isn't necessary at LibreSign scope and show the follow message:
> FINE Config file conf/conf.properties doesn't exists.
Isn't possible suppress the usage of this file and to prevent this message, I created a temporary file. JSignPdf don't will get nothing from this file because using at CLI, we always send all the necessary properties to the command.

chore: hide JSignPDF config check

---

lib/Listener/NotificationListener.php
lib/Notification/Notifier.php

The 'Dismiss notification' button was not appearing due to a rendering issue. This commit ensures the button is correctly displayed after a file is signed.
| Before: | After: |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/6e76b3ea-1bf8-49f9-a5a0-6e8dfc977a63" alt="before" /> | <img src="https://github.com/user-attachments/assets/5b29763e-c7d3-4ab5-a0ef-66e09f9fdfd3" alt="after" /> |
- Bugfix

fix: show 'Dismiss notification' button on signed file notification

---

lib/Service/SignatureTextService.php
tests/php/Unit/Handler/SignEngine/JSignPdfHandlerTest.php
tests/php/Unit/Service/SignatureTextServiceTest.php

Before this PR, when we open `Administration Settings > LibreSign` and the installation of extension Imagick haven't access to any ttf font, throws the follow error:
```xml
<?xml version="1.0"?>
<ocs>
<meta>
<status>failure</status>
<statuscode>400</statuscode>
<message></message>
</meta>
<data>
<error>No fonts available at system</error>
</data>
</ocs>
```
As fallback, I added the packed DejaVuSerif font and implemented an unit test to verify if mpdf have this font.
I used this font because we already pack this font with LibreSign and the test is to prevent problems if this font is renamed, moved or removed from mpdf.

fix: fallback when system haven't a TTF font

---

src/Components/Request/AccountOrEmail.vue

This pull request implements a 500ms debounce on the signer search field, previously each keystroke triggered an API request, This update improves the performance by reducing unnecessary API request. 
I Implemented debounce in the asyncFind method. I renamed the original asyncFind method to _asyncFind to separate the functionality, then I placed the asyncFind method wrapped in a 500ms debounce function, and imported debounce from the debounce package near the top of the file. 
You can manually test this by going to the LibreSign tab in NextCloud, open your browser's develop tools -> go to Network -> filter by "Fetch/XHR", then quickly type into the signer search input field, you should see one API request sent only after you stop typing. Previously, an API request was sent on every …

fix: implemented debounce on signer search field

---

appinfo/info.xml

For better visibility to users (who will not visit github page)
For preview of result see for example https://apps.nextcloud.com/apps/passwords
URL copied from "Sponsor this project" section.

docs: add donation link to appear on Nextcloud appstore

---

.l10nignore

```php
echo count(array_filter($translatableFiles, fn($v) => strpos($v, "vendor-bin")));
```
Output: 9320
After this change was found any entry with vendor-bin
```php
echo count(array_filter($translatableFiles, fn($v) => strpos($v, "vendor-bin")));
```
Output: 0
This could affect the translatable strings that is send do Transifex.

fix: ignore vendor bin at transifex sync

---

src/views/Validation.vue

- Bugfix
The document object came from backend with content every time. If the backend return invalid file content, will have a key inside this array and need to be ignored. Considering that the name is returned every time, I used this to check if is a valid answer or not.
Considering that is a frontend fix and that we haven't any test at frontend side, this PR only will have handmade tests.
How to reproduce:
```gherkin
Scenario: Validate with success
When sign a file
And go to validation page
Then You will see that the file is valid
Scenario: Validate with deleted file
When sign a file
And delete the file ".signed.pdf"
And go to validation page
Then you need to see the components to validate a new file
```
|---|---| …

fix: validate file answer

---

.github/workflows/reuse.yml

Potential fix for [https://github.com/LibreSign/libresign/security/code-scanning/5](https://github.com/LibreSign/libresign/security/code-scanning/5)
To fix the issue, we need to add a `permissions` block to the workflow. Since the workflow performs a compliance check and does not modify repository contents, the minimal permissions required are `contents: read`. This block should be added at the root level of the workflow to apply to all jobs, as there is only one job in this workflow. This change ensures that the `GITHUB_TOKEN` operates with restricted privileges, adhering to the principle of least privilege.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 5: Workflow does not contain permissions

---

.github/workflows/appstore-build-publish.yml

Potential fix for [https://github.com/LibreSign/libresign/security/code-scanning/1](https://github.com/LibreSign/libresign/security/code-scanning/1)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the minimal permissions required for the workflow to function correctly. Based on the operations performed in the workflow, the following permissions are recommended:
- `contents: read` for reading repository contents.
- `actions: write` for uploading artifacts and interacting with GitHub Actions.
- `packages: write` for publishing packages if necessary.
The `permissions` block can be added at the root level of the workflow to apply to all jobs, or within the `build_and_publish` job to limit its scope.
_Suggested fixes powered by Copilot Autofix. …

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

.github/workflows/appstore-build-publish.yml
CHANGELOG.md

[stable30] fix: build and publish workflow permission

---

tests/php/Unit/Handler/SignEngine/Pkcs12HandlerTest.php
tests/php/Unit/Helper/ValidateHelperTest.php
tests/php/Unit/Service/AccountServiceTest.php
tests/php/Unit/Service/MailServiceTest.php
tests/php/Unit/Service/RequestSignatureServiceTest.php
tests/php/Unit/Service/SignFileServiceTest.php

Pull Request Description
This pull request refactors all deprecated usages of the PHPUnit method ->will($this->returnValue(...)) to the modern syntax ->willReturn(...).
A total of 37 instances were updated across the codebase to comply with newer PHPUnit versions and eliminate warnings.
Related Issue
Issue Number: Closes #5242
Pull Request Type
Refactoring (no functional changes, no api changes)
Pull request checklist
-  Did you explain or provide a way of how can we test your code ?
Reply: Run the existing PHPUnit test suite to confirm no regressions.
-  If your pull request is related to frontend modifications provide a print of before and after screen
Reply: Not applicable (backend/test refactor only)
-  Did you provide a general summary of your changes ?
Reply: Yes, see Pull Request …

refactor: replace deprecated PHPUnit returnValue() with willReturn() 

---

.github/workflows/phpunit-sqlite.yml
CHANGELOG.md

[stable31] chore(deps): Bump coverallsapp/github-action from 2.0.0 to 2.3.6

---

.github/workflows/phpunit-sqlite.yml

[stable30] chore(deps): Bump coverallsapp/github-action from 2.0.0 to 2.3.6

---

tests/php/Unit/Helper/ValidateHelperTest.php
tests/php/Unit/Service/AccountServiceTest.php
tests/php/Unit/Service/MailServiceTest.php
tests/php/Unit/Service/RequestSignatureServiceTest.php
tests/php/Unit/Service/SignFileServiceTest.php
tests/php/Unit/Settings/AdminSettingsTest.php

- Replaced `->will($this->returnArgument())` with `->willReturnArgument()`  
- Replaced `->will($this->returnCallback())` with `->willReturnCallback()`
- Replaced `->will($self->returnValue())` with `->willReturn()` in data providers
- Replaced `->will($self->returnCallback())` with `->willReturnCallback()` in data providers
- ✅ Forward compatibility with newer PHPUnit versions
- ✅ Eliminates PHPUnit deprecation warnings  
- ✅ Cleaner, more readable test code
All existing functionality preserved - these are purely syntax updates to use modern PHPUnit methods.
Issue Number: #5261 
- Code style update (formatting, renaming)

Replace deprecated PHPUnit methods

---

src/store/files.js

Currently, some buttons are displayed **too early** when opening the sidebar in the Files app.
These buttons only make sense after all the necessary data has been loaded from the LibreSign API.
A few seconds later, once the API response arrives, the application can correctly determine whether the buttons should be displayed or not.
* Buttons appear before the API response.
* This causes users to see options that should not be available yet.
**Before fix** (buttons are shown even before the API returns data): <img width="549" height="271" alt="without fix" src="https://github.com/user-attachments/assets/fe8d1bf1-7c8c-49d3-8e74-532c948af2e8" />
**After fix** (buttons are hidden until the API response is ready): 
- Bugfix

fix: prevent show add signers early

---

src/Components/RightSidebar/AppFilesTab.vue
src/Components/RightSidebar/RequestSignatureTab.vue

The right sidebar now have a button to open file at Viewer app. When we stay at LibreSign file, works fine because we generate a LibreSign route to view the PDF file using the LibreSign UUID, when we stay at app Files, isn't the same because we haven't a LibreSign file and need to generate the file URL using the webdav URL.
Ref. #5368
- Bugfix
<details>
- After that, the terminal will show the build …

fix: open file at app files

---

src/store/files.js

In the Files app, users should be able to open the LibreSign tab even with non-LibreSign files to start the sign flow.
The condition was introduced in the last release because the same sidebar tab is used in the LibreSign app, where the file is always a LibreSign file.
To reproduce this:
Go to app Files
Upload a new PDF file
Click over this file and go to open in LibreSign file
The expected is to see the button "Add signer"
|---|---|
|<img width="501" height="237" alt="Screenshot_20250831_094809" src="https://github.com/user-attachments/assets/04156a3e-4255-43c4-9a52-a001ba1404f5" />|<img width="523" height="247" alt="Screenshot_20250831_094715" src="https://github.com/user-attachments/assets/f4aec2d3-c032-4634-a243-14eb37028b22" />|
Ref. #5362
- Bugfix
<details> …

fix: remove condition that restricts LibreSign tab to LibreSign files

---

lib/Handler/SignEngine/Pkcs12Handler.php
lib/Service/PdfParserService.php

Servers whose time zone is not UTC will receive "Invalid signingTime in certificate chain. We found Marty McFly" error.
pdfsig and pdfinfo commands TZ=UTC variable with when executed problem fixed
NextCloud 31
LibreSign 11.3.2
Issue Number: #5347
- Bugfix

Set TZ=UTC for pdfsig and pdfinfo command

---

lib/Handler/SignEngine/Pkcs12Handler.php

Close #5347
- Bugfix
<details>
- After that, the terminal will show the build process.
- Wait until you see the message:  
```bash
✍️ LibreSign is up!
```
This may take a few minutes.
- Open the **Ports** tab (next to the **Terminal**).
- Look for the service running on port **80**.
- Hover over the URL and click the **globe icon** 🌐 to open it in your browser.
- If you want to share the app with …

fix: use UTC as timezone when read data from signed document

---

.github/dependabot.yml

This PR updates the `.github/dependabot.yml` configuration to include all directories that contain a `composer.json` file.
Currently, Dependabot only checks the root directory for Composer dependencies, which causes it to miss several others in subdirectories (like `/vendor-bin/*` and `/tests/integration`). This change ensures that dependencies in all relevant project locations are now tracked and kept up-to-date automatically.
Resolves #5464
Issue Number: #5464 
- Feature
<details>
- Click **"Create …

feat(dependabot): add missing composer paths to config

---

tests/php/Unit/Handler/FooterHandlerTest.php

The unit test is getting the text into the original language and the string in Greek was translated now.
Was necessary to use raw to don't receive entities and be possible to compare.

fix: unit test after translation update
